<?php $this->headTitle('详情页') ?>
<?php $this->headTitle('系统操作日志') ?>
<?php $this->headLink()->appendStylesheet('/assets/default/xt-log/detail.css') ?>
<?php $this->headScript()->appendFile('/assets/default/xt-log/detail.js') ?>

<?php $d = $this->data ?>

<div class="container" style="margin-top:40px">
    
    <div class="row">
    
        <div class="col-lg-9 col-lg-9 col-sm-12 col-xs-12">
        
            <div class="page-header">
              <h1>系统操作日志详情页 <small>Detail of XtLog</small></h1>
            </div>
        
            <table class="table table-hover table-bordered table-rounded table-striped">
				<tr>
					<th>数据编号</th>
					<td><?php echo $d->id ?></td>
				</tr>
				<tr>
					<th>资源ID</th>
					<td><?php echo $d->resource_id ?></td>
				</tr>
				<tr>
					<th>资源名称</th>
					<td><?php echo $d->resource_name ?></td>
				</tr>
				<tr>
					<th>用户ID</th>
					<td><?php echo $d->sys_user_id ?></td>
				</tr>
				<tr>
					<th>用户名称</th>
					<td><?php echo $d->sys_user_name ?></td>
				</tr>
				<tr>
					<th>请求内容</th>
					<td><?php echo $d->request_data ?></td>
				</tr>
				<tr>
					<th>操作时间</th>
					<td><?php echo $d->log_time ?></td>
				</tr>
				<tr>
					<th>来源IP</th>
					<td><?php echo $d->ip ?></td>
				</tr>
            </table>
        
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">[面板模板]</h3>
                </div>
                <div class="panel-body">
                    ［面板内容面板内容面板内容面板内容面板内容面板内容面板内容面板内容面板内容面板内容面板内容］
                </div>
            </div>
        
        </div>
        
        
        <div class="col-lg-3 col-lg-3 col-sm-12 col-xs-12">
            <div class="list-group">
                <a href="#" class="list-group-item active">其它系统操作日志</a>
                <?php if ($this->topData): foreach ($this->topData as $t): ?>
                <a href="/xt-log/detail/id/<?php echo $t->id ?>" class="list-group-item">系统操作日志<?php echo $t->id ?></a>
                <?php endforeach; endif; ?>
            </div>
            
        </div>
    
    </div>

</div>