<?php $this->headTitle('修改密码')?>
<?php $this->headScript()->appendFile('/assets/admin/sys-user/change-pwd.js?t='.time())?>
<?php

$auth = Zend_Auth::getInstance();
$sysUser = $auth->getIdentity();
$sysUserId = $sysUser->id;
?>

<div class="row" style="text-align: center;">
	<div class="col-md-6">
		<div class="panel panel-default">
			<div class="panel-heading">修改密码</div>
			<div class="panel-body">

				<form class="form-horizontal">
					<div class="form-group">
						<label class="col-sm-2 control-label">原密码</label>
						<div class="col-sm-10">
							<input type="password" class="form-control" id="old_password" placeholder="请输入原密码">
						</div>
					</div>
					<div class="form-group">
						<label for="inputPassword" class="col-sm-2 control-label">新密码</label>
						<div class="col-sm-10">
							<input type="password" class="form-control" id="new_password_1" placeholder="请输入新密码">
						</div>
					</div>
					<div class="form-group">
						<label for="inputPassword" class="col-sm-2 control-label">确认密码</label>
						<div class="col-sm-10">
							<input type="password" class="form-control" id="new_password_2" placeholder="请输入新密码">
						</div>
					</div>
					<button type="button" id="commit" data-sys_user_id="<?php echo $sysUserId?>" class="btn btn-success">确认</button>
				</form>

			</div>
		</div>







	</div>
</div>