<!doctype html>
<html lang="zh">
<head>
<meta charset="utf-8">
<style type="text/css">
table td, table th {
	border: 1px solid #000;
}
</style>
</head>
<body>
	<table>
		<thead>
			<tr>
						<th>显示名称</th>
						<th>用户账户</th>
						<th>用户密码加密后</th>
						<th>加密标识</th>
						<th>关联类型(1:商家2:顾问3:供应商4:分销商)</th>
						<th>关联名称</th>
						<th>创建时间</th>
						<th>用户状态</th>
			</tr>
		</thead>
		<tbody>
            <?php if ($this->data): foreach($this->data as $d):?>
            <tr>
						<td><?php echo $d->realname ?></td>
						<td><?php echo $d->username ?></td>
						<td><?php echo $d->password ?></td>
						<td><?php echo $d->salt ?></td>
						<td><?php echo $d->associate_type ?></td>
						<td><?php echo $d->associate_name ?></td>
						<td><?php echo date("Y-m-d", strtotime($d->create_time)) ?></td>
						<td><?php echo $d->status ?></td>
			</tr>
            <?php endforeach; endif; ?>
        </tbody>
	</table>
</body>
</html>
