<?php $this->headTitle('查看页') ?>
<?php $this->headTitle('系统用户') ?>
<?php $this->headLink()->appendStylesheet('/assets/admin/sys-user/view.css') ?>
<?php $this->headScript()->appendFile('/assets/admin/sys-user/view.js') ?>

<?php $d = $this->data ?>

<div class="page-subheading page-subheading-md">
    <ol class="breadcrumb">
        <li><a href="javascript:;">控制面板</a></li>
        <li><a href="/admin/sys-user/manage">系统用户管理</a></li>
        <li class="active"><a href="javascript:;">查看</a></li>
    </ol>
</div>
<div class="page-heading page-heading-md">
    <h2><i class="fa fa-info-circle"></i> 系统用户详情 <a href="javascript: history.go(-1)" class="btn btn-default">
    	    <i class="fa fa-chevron-left"></i> 返回</a></h2>
</div>

<div class="container-fluid-md">
    <div class="panel panel-success">
        <div class="panel-heading">
            <h4 class="panel-title"><i class="fa fa-info-circle"></i> 系统用户</h4>

            <div class="panel-options">
                <a href="#" data-rel="collapse"><i class="fa fa-fw fa-minus"></i></a>
                <a href="#" data-rel="close"><i class="fa fa-fw fa-times"></i></a>
            </div>
        </div>
        <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-striped table-hover table-detail-view">
                    <tbody>
				<tr>
					<th>显示名称</th>
					<td><?php echo $d->realname ?></td>
				</tr>
				<tr>
					<th>用户账户</th>
					<td><?php echo $d->username ?></td>
				</tr>
				<tr>
					<th>用户密码加密后</th>
					<td><?php echo $d->password ?></td>
				</tr>
				<tr>
					<th>加密标识</th>
					<td><?php echo $d->salt ?></td>
				</tr>
				<tr>
					<th>关联类型(1:商家2:顾问3:供应商4:分销商)</th>
					<td><?php echo $d->associate_type ?></td>
				</tr>
				<tr>
					<th>关联名称</th>
					<td><?php echo $d->associate_name ?></td>
				</tr>
				<tr>
					<th>创建时间</th>
					<td><?php echo date("Y-m-d", strtotime($d->create_time)) ?></td>
				</tr>
				<tr>
					<th>用户状态</th>
					<td><?php echo $d->status ?></td>
				</tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>