<?php $this->headTitle('详情页') ?>
<?php $this->headTitle('我的收藏') ?>
<?php $this->headLink()->appendStylesheet('/assets/wx/collect/detail.css') ?>
<?php $this->headScript()->appendFile('/assets/wx/collect/detail.js') ?>

<?php $d = $this->data ?>

<div class="container" style="margin-top:40px">
    
    <div class="row">
    
        <div class="col-xs-9">
        
            <div class="page-header">
              <h1>我的收藏详情页 <small>{ACTION} of {MODEL_NAME}</small></h1>
            </div>
        
            <table class="table table-hover table-bordered table-rounded table-striped">
                <tr>
				<tr>
					<th>数据ID</th>
					<td><?php echo $d->id ?></td>
				</tr>
				<tr>
					<th>用户ID</th>
					<td><?php echo $d->user_id ?></td>
				</tr>
				<tr>
					<th>openid</th>
					<td><?php echo $d->openid ?></td>
				</tr>
				<tr>
					<th>医生ID</th>
					<td><?php echo $d->doctor_id ?></td>
				</tr>
				<tr>
					<th>医生姓名</th>
					<td><?php echo $d->doctor_name ?></td>
				</tr>
				<tr>
					<th>医生职称</th>
					<td><?php echo $d->doctor_call ?></td>
				</tr>
				<tr>
					<th>所在科室</th>
					<td><?php echo $d->department ?></td>
				</tr>
				<tr>
					<th>日期</th>
					<td><?php echo $d->date ?></td>
				</tr>
                </tr>
            </table>
        
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">[面板模板]</h3>
                </div>
                <div class="panel-body">
                    ［面板内容面板内容面板内容面板内容面板内容面板内容面板内容面板内容面板内容面板内容面板内容］
                </div>
            </div>
        
        </div>
        
        
        <div class="col-xs-3">
            <div class="list-group">
                <a href="#" class="list-group-item active">推荐我的收藏</a>
                <?php if ($this->topData): foreach ($this->topData as $t): ?>
                <a href="/collect/detail/id/<?php echo $t->id ?>" class="list-group-item">推荐我的收藏<?php echo $t->id ?></a>
                <?php endforeach; endif; ?>
            </div>
            
        </div>
    
    </div>

</div>