<?php $this->headTitle('就诊服务') ?>
<?php $this->headLink()->appendStylesheet('/assets/wx/treat-service/index/index.css') ?>
<?php $this->headLink()->appendStylesheet('/assets/wx/treat-service/index/swiper.min.css') ?>
<div class="page" style="opacity: 1;">
    <div class="banner swiper-container-horizontal">
        <div class="swiper-wrapper" style="transform: translate3d(-640px, 0px, 0px); transition-duration: 0ms;">
            <div class="swiper-slide swiper-slide-prev" style="width: 640px;"><img src="/assets/wx/treat-service/index/1-banner1.png"></div>
            <div class="swiper-slide swiper-slide-active" style="width: 640px;"><img src="/assets/wx/treat-service/index/2-banner1.png"></div>
        </div>
    </div>
    <div class="list">
        <ul class="">
            <a  href="/wx/treat-service/related-card" >
                <li style="touch-action: manipulation; -webkit-user-select: none; -webkit-user-drag: none; -webkit-tap-highlight-color: rgba(0, 0, 0, 0);">
                    <img src="http://smdyyy.wx.191cn.com/yjy/img/first-list-registration.png" href="html/office.html" data-card="1">
                    <span data-card="1" href="html/office.html">预约挂号</span>
                </li>
            </a>
            <a  href="/wx/treat-service/related-card" >
                <li style="touch-action: manipulation; -webkit-user-select: none; -webkit-user-drag: none; -webkit-tap-highlight-color: rgba(0, 0, 0, 0);">
                    <img src="http://smdyyy.wx.191cn.com/yjy/img/first-list-prepayment.png" href="html/prepayment.html" data-card="1">
                    <span data-card="1" href="html/prepayment.html">预交金充值</span>
                </li>
            </a>
            <a  href="/wx/treat-service/related-card" >
                <li style="touch-action: manipulation; -webkit-user-select: none; -webkit-user-drag: none; -webkit-tap-highlight-color: rgba(0, 0, 0, 0);">
                    <img src="http://smdyyy.wx.191cn.com/yjy/img/second-list-list.png" href="html/inventory.html" data-card="1">
                    <span data-card="1" href="html/inventory.html">门诊清单</span>
                </li>
            </a>
        </ul>
    </div>
    <div class="divider"></div>
    <div class="second-list">
        <ul>
            <a href="/wx/department-intro/index">
                <li style="background-image: url(&quot;http://smdyyy.wx.191cn.com/yjy/img/second-list-office.png&quot;);">科室介绍</li>
            </a>
            <a href="/wx/expert-intro/index">
                <li style="background-image: url(&quot;http://lcxyy.191cn.com/yjy/img/second-list-expert.png&quot;);">专家介绍</li>
            </a>
            <a href="/wx/news/attendance-guide">
                <li style="background-image: url(&quot;http://smdyyy.wx.191cn.com/yjy/img/second-list-guide.png&quot;);">就诊指南</li>
            </a>
            <a href="">
                <li style="background-image: url(&quot;http://smdyyy.wx.191cn.com/yjy/img/second-list-price.png&quot;);">价目查询</li>
            </a>
            <a href="">
                <li style="background-image: url(&quot;http://smdyyy.wx.191cn.com/yjy/img/second-list-notice.png&quot;);">注意事项</li>
            </a>
            <a href="">
                <li style="background-image: url(&quot;http://smdyyy.wx.191cn.com/yjy/img/second-list-intro.png&quot;);">医院简介</li>
            </a>
            <a href="">
                <li style="background-image: url(&quot;http://lcxyy.191cn.com/yjy/img/second-list-ai.png&quot;);">智能导诊</li>
            </a>
            <a href="">
                <li style="background-image: url(&quot;http://smdyyy.wx.191cn.com/yjy/img/second-list-baike.png&quot;);">健康百科</li>
            </a>
            <a href="">
                <li style="background-image: url(&quot;http://smdyyy.wx.191cn.com/yjy/img/second-list-navigation.png&quot;);">医院导航</li>
            </a>
            <a href="">
                <li style="background-image: url(&quot;undefined&quot;);"></li>
            </a>
        </ul>
    </div>
    <div class="divider"></div>
    <div class="text-block" style="display: none;">
        <div class="content">
            <p class="title"></p>
            <i class="icon-close"></i>
            <div class="intro">
                <p></p>
            </div>
        </div>
    </div>
</div>
<div class="footer">
    <ul>
        <a href="/wx/treat-service/index"><li class="active"> 服务</li></a>
        <a href="/wx/person/index"><li>我</li></a>
    </ul>
</div>