<?php $this->headTitle('线上签约') ?>
<?php $this->headLink()->appendStylesheet('/assets/wx/treat-service/related-card/related-card.css') ?>
<?php $this->headScript()->appendFile('/assets/wx/treat-service/related-card/related-card.js') ?>
<style>
*,body{font-size:14px !important}
</style>
<div class="page" id="data" style="opacity: 1;">
    <ul class="filtrate-box">
        <li class="active select" data-type="1">
            <p>社保卡</p>
        </li>
        <li data-type="2">
            <p>身份证</p>
        </li>
    </ul> 
    <form>
        <input type="hidden" id="type" name="type" value="1">
        <input class="input" type="text" id="name" name="name" placeholder="姓名">
        <input class="input" type="text" id="card" name="card"  placeholder="身份证号码">
        <input class="input" type="text" id="cardNo" name="cardNo"  placeholder="卡号">
        <p class="hospital">发卡医院:济南市第三人民医院</p>
    </form>
    <div>
        <a href="javascript:;" class="weui-btn weui-btn_primary">立即签约</a>
    </div>
</div>
