<?php $this->headTitle('医院服务') ?>
<?php $this->headLink()->appendStylesheet('/assets/wx/treat-service/index/index.css?t='.time()) ?>
<link href="http://libs.baidu.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet">
<script src="http://libs.baidu.com/jquery/2.0.0/jquery.min.js"></script>
<script src="http://libs.baidu.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
<script> 
$(document).ready(function(){ 
	$('#circleContent').carousel({interval:5000});//每隔5秒自动轮播 
}); 
</script>
<div class="page grid js_show">
    <div class="page__hd">
       <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
          <!-- Indicators -->
        <!--   <ol class="carousel-indicators">
             <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
             <li data-target="#carousel-example-generic" data-slide-to="1"></li>
          </ol> -->
          <!-- Wrapper for slides -->
          <div class="carousel-inner" role="listbox">
             <div class="item active">
                <img src="/assets/wx/treat-service/index/banner.jpg">
             </div>
             <div class="item">
                <img src="/assets/wx/treat-service/index/banner.jpg">
             </div>
          </div>
        
        </div>
    </div>
    <div class="weui-grids">
        <a href="/wx/website/detail" class="weui-grid">
            <div class="weui-grid__icon" style="    width: 55px;">
                <img src="/assets/wx/img/hospital-service/yiyuanjieshao.svg">
            </div>
            <p class="weui-grid__label">医院介绍</p>
        </a>
        <a href="/wx/department-intro/index" class="weui-grid">
            <div class="weui-grid__icon">
                <img src="/assets/wx/img/hospital-service/keshijieshao.svg">
            </div>
            <p class="weui-grid__label">科室介绍</p>
        </a>
        <a href="/wx/expert-intro/index" class="weui-grid">
            <div class="weui-grid__icon">
                <img src="/assets/wx/img/hospital-service/zhuanjiajieshao.svg">
            </div>
            <p class="weui-grid__label">专家介绍</p>
        </a>
    </div>
   <div class="page__bd page__bd_spacing">
        <div class="weui-flex">
            <div class="weui-flex__item"><a href="/wx/website/list"><div class="placeholder"><img src="/assets/wx/img/hospital-service/xinwen.svg">院内新闻</div></a></div>
            <div class="weui-flex__item"><a href="/wx/website/route"><div class="placeholder"><img src="/assets/wx/img/hospital-service/yindao.svg">来院导引</div></a></div>
        </div>
        <div class="weui-flex">
            <div class="weui-flex__item"><a href="https://his.ipalmap.com/send-template-new/index.html#/search?name=jinanshilisanyuan"><div class="placeholder"><img src="/assets/wx/img/hospital-service/ditu.svg">院内地图</div></a></div>
            <div class="weui-flex__item"><a href="/wx/news/list/type/1"><div class="placeholder"><img src="/assets/wx/img/hospital-service/fuwu.svg">周边服务</div></a></div>
        </div>
        <div class="weui-flex">
            <div class="weui-flex__item"><a href="/wx/news/attendance-guide"><div class="placeholder"><img src="/assets/wx/img/hospital-service/liucheng.svg">就诊流程</div></a></div>
            <div class="weui-flex__item"><a href="/wx/news/list/type/3"><div class="placeholder"><img src="/assets/wx/img/hospital-service/zhuyi.svg">注意事项</div></a></div>
        </div>
        <div class="weui-flex">
            <div class="weui-flex__item"><a href="/wx/feature-major/list"><div class="placeholder"><img src="/assets/wx/img/hospital-service/tese.svg">特色专业</div></a></div>
            <div class="weui-flex__item"><a href="/wx/feature-skill/list"><div class="placeholder"><img src="/assets/wx/img/hospital-service/teseyiji.svg" style="    width: 16px;">特色医技</div></a></div>
        </div>
    </div>
</div>