<?php $this->headTitle('住院缴费') ?>
<?php $this->headLink()->appendStylesheet('/assets/wx/in-hospital/cost-list.css') ?>
<?php //$this->headScript()->appendFile('/assets/wx/abouts/list.js') ?>

<div class="weui-panel__bd"> 信息已登记成功！请缴纳住院预缴金！</div>

<div class="page__bd">
    <div class="weui-form-preview">
        <div class="weui-form-preview__bd">
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">姓名</label>
                <span class="weui-form-preview__value red">孙晓亮</span>
            </div>
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">民族</label>
                <span class="weui-form-preview__value black">汉族</span>
            </div>
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">居住地址</label>
                <span class="weui-form-preview__value red">山东省济南市</span>
            </div>
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">身份证</label>
                <span class="weui-form-preview__value red">370785199512254578</span>
            </div>
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">婚姻状况</label>
                <span class="weui-form-preview__value black">未婚</span>
            </div>
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">手机</label>
                <span class="weui-form-preview__value red">15945784578</span>
            </div>
             <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">家属姓名</label>
                <span class="weui-form-preview__value red">李红</span>
            </div>
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">家属关系</label>
                <span class="weui-form-preview__value black">母亲</span>
            </div>
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">家属地址</label>
                <span class="weui-form-preview__value red">山东省济宁市</span>
            </div>
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">家属电话</label>
                <span class="weui-form-preview__value red">18215478548</span>
            </div>
        </div>
        <div class="weui-form-preview__bd">
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">科室</label>
                <span class="weui-form-preview__value red">呼吸内科</span>
            </div>
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">床位号</label>
                <span class="weui-form-preview__value black">56号</span>
            </div>
        </div>
        <div class="weui-flex">
            <div class="weui-flex__item"><div class="placeholder">缴费金额：<span>2000元</span></div></div>
            <div class="weui-flex__item"><a href="javascript:;" class="weui-btn weui-btn_primary">立即支付</a></div>
        </div>
    </div>
</div>