<?php $this->headTitle('友情提示') ?>
<?php $this->headLink()->appendStylesheet('/assets/wx/satisfaction/warn.css?t='.time()) ?>
<style>
.weui-icon_msg-primary.weui-icon-warn{
	color:#FFBE00
}.icon-box__ctn {
    margin-top: 5%;
}
</style>

<div class="page icons js_show">
    <div class="page__bd page__bd_spacing">
		<i class="weui-icon-warn weui-icon_msg-primary"></i>
        <div class="icon-box__ctn">
            <p class="icon-box__desc">请于8月1日正式使用本公众号</p>
        </div>
    </div>
</div>