<?php $this->headTitle('就诊人详情') ?>
<?php $this->headLink()->appendStylesheet('/assets/wx/user-info/detail.css?t='.time()) ?>
<?php $this->headScript()->appendFile('/assets/wx/user-info/detail.js?t='.time()) ?>
 
<?php $d = $this->data ?>
<style>
.weui-form-preview__label {
    margin-right: 1.5em;
}
</style>
<div class="page preview js_show">
    <div class="page__hd">
        <img class="weui-media-box__thumb" src="/assets/wx/user-info/icon.png" alt="">
        <h4 class="weui-media-box__title">张三</h4>
    </div>
    <div class="page__bd">
        <div class="weui-form-preview">
            <div class="weui-form-preview__bd">
                <div class="weui-form-preview__item" style="text-align: left">
                    <label class="weui-form-preview__label">性别	</label>
                    <span class="weui-form-preview__value">女</span>
                </div>
                <div class="weui-form-preview__item" style="text-align: left">
                    <label class="weui-form-preview__label">手机号</label>
                    <span class="weui-form-preview__value">18515947894</span>
                </div>
                <div class="weui-form-preview__item" style="line-height: 2;margin-top: 3%;text-align: left;">
                    <label class="weui-form-preview__label">地址</label>
                    <span class="weui-form-preview__value">山东省临沂市兰山区</span>
                </div>
                <div class="weui-form-preview__item" style="line-height: 2;margin-top: 3%;text-align: left; ">
                    <label class="weui-form-preview__label">就诊卡号</label>
                    <span class="weui-form-preview__value">无卡</span>
                </div>
            </div>
            <div class="weui-form-preview__ft">
                <a class="weui-form-preview__btn weui-form-preview__btn_primary" id="delete"">解除绑定</a>
            </div>
        </div>
    </div>
</div>