<?php $this->headTitle('线上签约') ?>
<?php $this->headLink()->appendStylesheet('/assets/wx/user-info/related-card.css?t='.time()) ?>
<?php $this->headScript()->appendFile('/assets/wx/user-info/related-card.js?t='.time()) ?>
<style>
*, body {
    background: none; 
}

</style>
<div class="page" id="data" style="opacity: 1;">
    <ul class="filtrate-box">
        <li class="active select"  data-type="1"><p>就诊卡</p></li>
        <li data-type="2"><p>身份证</p></li>
        <li data-type="3"><p>儿童</p></li>
    </ul> 
    <form>
        <input type="hidden" id="bind_type" name="bind_type" value="1">
        <input class="input" type="text" id="name" name="name" placeholder="姓名">
        <input class="input" type="date" id="birthday" name="birthday" placeholder="出生年月日" value="出生年月">
        <input class="input" type="text" id="guardian" name="guardian" placeholder="监护人姓名">
        <input class="input" type="text" id="card" name="card"  placeholder="身份证号（含字母需大写）">
        <input class="input" type="text" id="phone" name="phone"  placeholder="手机号">
        <input class="input" type="text" id="cardNo" name="cardNo"  placeholder="就诊卡号">
        <div class="weui-cells weui-cells_form">
            <div class="weui-cell">
                <div class="weui-cell__hd"><label class="weui-label"></label></div>
                <div class="weui-cell__bd">
                <?php if($this->count <= 0):?><input type="radio" name="type" value="1" checked>本人<?php endif;?>
            	</div>
                <div class="weui-cell__bd"  style="margin-left: 9%;">
                	<input type="radio" name="type" value="2" <?php if($this->count>0):?>checked<?php endif;?>>他人
                </div>
            </div>
        </div>
        <p class="hospital" style="line-height: normal;">发卡医院：临沂市人民医院<br></p>
    </form>
    <div>
        <a href="javascript:;" class="weui-btn weui-btn_primary bindBtn">立即签约</a>
    </div>
</div>
