<?php $this->headTitle('查看页') ?>
<?php $this->headTitle('预约挂号取消信息') ?>
<?php $this->headLink()->appendStylesheet('/assets/admin/registration-cancel/view.css') ?>
<?php $this->headScript()->appendFile('/assets/admin/registration-cancel/view.js') ?>

<?php $d = $this->data ?>

<div class="page-subheading page-subheading-md">
    <ol class="breadcrumb">
        <li><a href="javascript:;">控制面板</a></li>
        <li><a href="/admin/registration-cancel/manage">预约挂号取消信息管理</a></li>
        <li class="active"><a href="javascript:;">查看</a></li>
    </ol>
</div>
<div class="page-heading page-heading-md">
    <h2>
        <i class="fa fa-info-circle"></i> 预约挂号取消信息详情 
        <a href="javascript: history.go(-1)" class="btn btn-default pull-right">
    	    <i class="fa fa-chevron-left"></i> 返回</a>
    </h2>
</div>

<div class="container-fluid-md">
    <div class="panel panel-default">
        <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-striped table-bordered table-detail-view">
                    <tbody>
				<tr>
					<th>openid</th>
					<td><?php echo $d->openid ?></td>
				</tr>
				<tr>
					<th>就诊时段</th>
					<td><?php echo $d->time ?></td>
				</tr>
				<tr>
					<th>费用类型</th>
					<td><?php echo $d->type ?></td>
				</tr>
				<tr>
					<th>医院名称</th>
					<td><?php echo $d->hospital_name ?></td>
				</tr>
				<tr>
					<th>就诊科室</th>
					<td><?php echo $d->department ?></td>
				</tr>
				<tr>
					<th>科室位置</th>
					<td><?php echo $d->address ?></td>
				</tr>
				<tr>
					<th>医生姓名</th>
					<td><?php echo $d->doctor_name ?></td>
				</tr>
				<tr>
					<th>医生职称</th>
					<td><?php echo $d->doctor_call ?></td>
				</tr>
				<tr>
					<th>就诊人</th>
					<td><?php echo $d->name ?></td>
				</tr>
				<tr>
					<th>是否有就诊卡</th>
					<td><?php echo $d->is_patient_card ?></td>
				</tr>
				<tr>
					<th>医院单号</th>
					<td><?php echo $d->hospital_number ?></td>
				</tr>
				<tr>
					<th>平台单号</th>
					<td><?php echo $d->platform_number ?></td>
				</tr>
				<tr>
					<th>交易金额</th>
					<td><?php echo $d->price ?></td>
				</tr>
				<tr>
					<th>支付状态</th>
					<td><?php echo $d->pay_status ?></td>
				</tr>
				<tr>
					<th>预约时间</th>
					<td><?php echo $d->appointment_time ?></td>
				</tr>
				<tr>
					<th>取消时间</th>
					<td><?php echo $d->cancel_time ?></td>
				</tr>
				<tr>
					<th>取消原因</th>
					<td><?php echo $d->cancel_cause ?></td>
				</tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>