<?php $this->headTitle('增加页') ?>
<?php $this->headTitle('新闻动态') ?>
<?php $this->headLink()->appendStylesheet('/assets/admin/news/add.css') ?>
<?php $this->headScript()->appendFile('/assets/admin/news/add.js') ?>
<?php $this->headScript()->appendFile('/assets/admin/news/validate-config.js') ?>

<div class="page-subheading page-subheading-md">
    <ol class="breadcrumb">
        <li><a href="javascript:;">控制面板</a></li>
        <li><a href="/admin/news/manage"><?php  if($this->type == 1):echo "周边服务";elseif ($this->type == 2):echo "就诊流程"; else:echo "注意事项";endif;?>管理</a></li>
        <li class="active"><a href="javascript:;">添加</a></li>
    </ol>
</div>
<div class="page-heading page-heading-md">
    <h2>
        <i class="fa fa-plus-circle"></i> 添加新的<?php  if($this->type == 1):echo "周边服务";elseif ($this->type == 2):echo "就诊流程"; else:echo "注意事项";endif;?> 
        <a href="javascript: history.go(-1)" class="btn btn-default pull-right">
    	    <i class="fa fa-chevron-left"></i> 返回</a>
    </h2>
</div>

<div class="container-fluid-md">
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h4 class="panel-title"><i class="fa fa-plus"></i> <?php  if($this->type == 1):echo "周边服务";elseif ($this->type == 2):echo "就诊流程"; else:echo "注意事项";endif;?></h4>

            <div class="panel-options">
            </div>
        </div>
        <div class="panel-body">
            <?php echo $this->form ?>
        </div>
    </div>
</div>