<!doctype html>
<html lang="zh">
<head>
<meta charset="utf-8">
<style type="text/css">
table td, table th {
	border: 1px solid #000;
}
</style>
</head>
<body>
	<table>
		<thead>
			<tr>
					<th>类型 type</th>
					<th>标题 title</th>
					<th>内容 intro</th>
					<th>日期 date</th>

			</tr>
		</thead>
		<tbody>
            <?php if ($this->data): foreach($this->data as $d):?>
            <tr>
					<td style="mso-number-format='\@'"><?php echo $d->type ?></td>
					<td style="mso-number-format='\@'"><?php echo $d->title ?></td>
					<td style="mso-number-format='\@'"><?php echo $d->intro ?></td>
					<td style="mso-number-format='yyyy-mm-dd'"><?php echo $d->date ? date("Y-m-d", strtotime($d->date)) : "" ?></td>
			</tr>
            <?php endforeach; endif; ?>
        </tbody>
	</table>
</body>
</html>
