<?php $this->headTitle('查看页') ?>
<?php $this->headTitle('新闻动态') ?>
<?php $this->headLink()->appendStylesheet('/assets/admin/news/view.css') ?>
<?php $this->headScript()->appendFile('/assets/admin/news/view.js') ?>

<?php $d = $this->data ?>

<div class="page-subheading page-subheading-md">
    <ol class="breadcrumb">
        <li><a href="javascript:;">控制面板</a></li>
        <li><a href="/admin/news/manage"><?php  if($this->type == 1):echo "周边服务";elseif ($this->type == 2):echo "就诊流程"; else:echo "注意事项";endif;?>管理</a></li>
        <li class="active"><a href="javascript:;">查看</a></li>
    </ol>
</div>
<div class="page-heading page-heading-md">
    <h2>
        <i class="fa fa-info-circle"></i><?php  if($this->type == 1):echo "周边服务";elseif ($this->type == 2):echo "就诊流程"; else:echo "注意事项";endif;?>详情 
        <a href="javascript: history.go(-1)" class="btn btn-default pull-right">
    	    <i class="fa fa-chevron-left"></i> 返回</a>
    </h2>
</div>

<div class="container-fluid-md">
    <div class="panel panel-default">
        <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-striped table-bordered table-detail-view">
                    <tbody>
				<tr>
					<th>类型</th>
					<td><?php echo $d->type ?></td>
				</tr>
				<tr>
					<th>标题</th>
					<td><?php echo $d->title ?></td>
				</tr>
				<tr>
					<th>内容</th>
					<td><?php echo $d->intro ?></td>
				</tr>
				<tr>
					<th>日期</th>
					<td><?php echo $d->date ? date("Y-m-d", strtotime($d->date)) : "" ?></td>
				</tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>