<?php $this->headTitle('数据导入') ?>
<?php $this->headTitle('医院介绍') ?>
<?php $this->headLink()->appendStylesheet('/assets/admin/abouts/import.css') ?>
<?php $this->headScript()->appendFile('/assets/admin/abouts/import.js') ?>

<div class="page-subheading page-subheading-md">
    <ol class="breadcrumb">
        <li><a href="javascript:;">控制面板</a></li>
        <li><a href="/admin/abouts/manage">医院介绍管理</a></li>
        <li class="active"><a href="javascript:;">导入</a></li>
    </ol>
</div>
<div class="page-heading page-heading-md">
    <h2>
        <i class="fa fa-cloud-upload"></i> 医院介绍导入 
        <a href="javascript: history.go(-1)" class="btn btn-default pull-right">
    	    <i class="fa fa-chevron-left"></i> 返回</a>
    </h2>
</div>

<div class="container-fluid-md">

    <?php if (count($this->messages) > 0): foreach ($this->messages as $message): ?>
    <div class="alert alert-<?php echo isset($message[1]) ? $message[1] : 'success' ?>">
        <?php echo $message[0] ?>
    </div>
    <?php endforeach; endif; ?>

    <div class="panel panel-primary">
        <div class="panel-heading">
            <h4 class="panel-title"><i class="fa fa-fw fa-cloud-upload"></i> 医院介绍导入</h4>

            <div class="panel-options">
            </div>
        </div>
        <div class="panel-body">
            <div class="table-responsive">
                <form action="" method="post" enctype="multipart/form-data">
                <table class="table table-striped">
                    <tbody>
                        <tr>
                            <td><i class="fa fa-fw fa-file-excel-o"></i> 选择数据文件</td>
                            <td><input name="data-file-upload" type="file"></td>
                        </tr>
                        <tr>
                            <td colspan="2" class="text-danger">
                                上传文件格式为.xls文件
                                <a href="/admin/abouts/export/id/0">《医院介绍模板 点此下载》</a>
                            </td>
                        </tr>
                        <tr>
                            <td colspan="2" class="text-muted">
                                注意：excel文件中数据列不可颠倒，请按照模板填写
                            </td>
                        </tr>
                        <tr>
                            <td colspan="2" class="text-center">
                                <button class="btn btn-primary" id="import-button">
                                    <i class="fa fa-fw fa-cloud-upload"></i> 开始导入
                                </button>
                            </td>
                        </tr>
                    </tbody>
                </table>
                </form>
            </div>
        </div>
    </div>
</div>