<?php $this->headTitle('查看页') ?>
<?php $this->headTitle('医院介绍') ?>
<?php $this->headLink()->appendStylesheet('/assets/admin/abouts/view.css') ?>
<?php $this->headScript()->appendFile('/assets/admin/abouts/view.js') ?>

<?php $d = $this->data ?>

<div class="page-subheading page-subheading-md">
    <ol class="breadcrumb">
        <li><a href="javascript:;">控制面板</a></li>
        <li><a href="/admin/abouts/manage">医院介绍管理</a></li>
        <li class="active"><a href="javascript:;">查看</a></li>
    </ol>
</div>
<div class="page-heading page-heading-md">
    <h2>
        <i class="fa fa-info-circle"></i> 医院介绍详情 
        <a href="javascript: history.go(-1)" class="btn btn-default pull-right">
    	    <i class="fa fa-chevron-left"></i> 返回</a>
    </h2>
</div>

<div class="container-fluid-md">
    <div class="panel panel-default">
        <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-striped table-bordered table-detail-view">
                    <tbody>
				<tr>
					<th>标题</th>
					<td><?php echo $d->title ?></td>
				</tr>
				<tr>
					<th>等级</th>
					<td><?php echo $d->class ?></td>
				</tr>
				<tr>
					<th>电话</th>
					<td><?php echo $d->phone ?></td>
				</tr>
				<tr>
					<th>地址</th>
					<td><?php echo $d->address ?></td>
				</tr>
				<tr>
					<th>介绍</th>
					<td><?php echo $d->intro ?></td>
				</tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>