<!doctype html>
<html lang="zh">
<head>
<meta charset="utf-8">
<style type="text/css">
table td, table th {
	border: 1px solid #000;
}
</style>
</head>
<body>
	<table>
		<thead>
			<tr>
						<th>数据ID</th>
						<th>角色ID</th>
						<th>资源ID</th>
			</tr>
		</thead>
		<tbody>
            <?php if ($this->data): foreach($this->data as $d):?>
            <tr>
						<td><?php echo $d->id ?></td>
						<td><?php echo $d->role_id ?></td>
						<td><?php echo $d->resource_id ?></td>
			</tr>
            <?php endforeach; endif; ?>
        </tbody>
	</table>
</body>
</html>
