<?php 
/**
 * 前端网站布局（默认布局）
 * @author [此处填写开发人员姓名]
 * @copyright  Copyright (c) 2014-2018 SZ Technologies China Inc. (http://www.jnszkj.com)
 * @version 1.0
 */
?>
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="renderer" content="webkit|ie-comp|ie-stand">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/favicon.ico">

    <?php echo $this->headTitle("接口说明文档 - 临沂市人民医院服务窗") ?>

    <!-- Bootstrap core CSS -->
    <link href="http://cdn.bootcss.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="http://cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="http://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <style>
    td, th {
    	border: 1px solid #000;
    	text-align:center;
    }
    </style>
  </head>

  <body>
   <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <div class="starter-template text-center">
                    <h1>接口说明文档</h1>
                    <p class="lead">API Documentation</p>
                </div>
                <hr />
                <div class="container">
                    <div class="row">
                        
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="http://cdn.bootcss.com/jquery/1.11.3/jquery.min.js"></script>
    <script src="http://cdn.bootcss.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="/assets/layout/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>