<?php $this->headTitle('查看页') ?>
<?php $this->headTitle('来院导引') ?>
<?php $this->headLink()->appendStylesheet('/assets/admin/route/view.css') ?>
<?php $this->headScript()->appendFile('/assets/admin/route/view.js') ?>

<?php $d = $this->data ?>

<div class="page-subheading page-subheading-md">
    <ol class="breadcrumb">
        <li><a href="javascript:;">控制面板</a></li>
        <li><a href="/admin/route/manage">来院导引管理</a></li>
        <li class="active"><a href="javascript:;">查看</a></li>
    </ol>
</div>
<div class="page-heading page-heading-md">
    <h2>
        <i class="fa fa-info-circle"></i> 来院导引详情 
        <a href="javascript: history.go(-1)" class="btn btn-default pull-right">
    	    <i class="fa fa-chevron-left"></i> 返回</a>
    </h2>
</div>

<div class="container-fluid-md">
    <div class="panel panel-default">
        <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-striped table-bordered table-detail-view">
                    <tbody>
				<tr>
					<th>公交路线</th>
					<td><?php echo $d->gj_route ?></td>
				</tr>
				<tr>
					<th>驾车路线</th>
					<td><?php echo $d->jc_route ?></td>
				</tr>
				<tr>
					<th>备注</th>
					<td><?php echo $d->intro ?></td>
				</tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>