<?php 
/**
 * 后台管理系统布局文件
 * @author liujin
 * @copyright  Copyright (c) 2014-2017 SZ Technologies China Inc. (http://www.jnszkj.com)
 * @version 1.0
 */
?>
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="renderer" content="webkit|ie-comp|ie-stand">
        <?php echo $this->headTitle("临沂市人民医院后台管理系统") ?> 
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width">
        <link rel="shortcut icon" href="/favicon.ico">
        <link rel="stylesheet" href="/template/dist/css/bootstrap.min.css">
        <link rel="stylesheet" href="/template/dist/css/iriy-admin.min.css">
        <link rel="stylesheet" href="/template/demo/css/demo.css">
        <link rel="stylesheet" href="/template/dist/assets/font-awesome/css/font-awesome.css">
        <link rel="stylesheet" href="/assets/layout/layout-admin-theme-blue.css">

        <?php
        // 选择性加载日期时间选择器
        if ($this->form && $this->form->getAttrib('load_datetimepicker')) :
        ?>
        <link rel="stylesheet" href="/libs/datetimepicker/css/bootstrap-datetimepicker.min.css">
        <?php endif; ?>
        
        <?php echo $this->headLink() ?>
        
        <!--[if lt IE 9]>
        <script src="/template/dist/assets/libs/html5shiv/html5shiv.min.js"></script>
        <script src="/template/dist/assets/libs/respond/respond.min.js"></script>
        <![endif]-->
<meta name="viewport" content="width=device-width, initial-scale=1,maximum-scale=1, user-scalable=no">
    </head>
    <body>
        <div class="page-wrapper">
            <div class="page-content">
                <?php echo $this->layout()->content ?>
            </div>
        </div>
        <script src="/template/dist/assets/libs/jquery/jquery.min.js"></script>
        <script src="/template/dist/assets/bs3/js/bootstrap.min.js"></script>
        <script src="/template/dist/assets/plugins/jquery-navgoco/jquery.navgoco.js"></script>
        <script src="/template/dist/assets/plugins/jquery-validation/jquery.validate.min.js"></script>
        <script src="/template/dist/js/main.js"></script>
        <script src="/assets/layout/layout-admin.js"></script>
        <script src="/assets/layout/page-component-acl.szkj.js"></script>

        <?php echo $this->headScript() ?>
        <?php
        // 选择性加载日期时间选择器
        if ($this->form && $this->form->getAttrib('load_datetimepicker')) :
        ?>
        <script src="/libs/datetimepicker/js/bootstrap-datetimepicker.min.js"></script>
        <script src="/libs/datetimepicker/js/locales/bootstrap-datetimepicker.zh-CN.js"></script>
        <script src="/libs/datetimepicker/js/bootstrap-datetimepicker.szkj.extend.js"></script>
        <?php endif; ?>
        <?php
        // 选择性加载UEditor编辑器
        if ($this->form && $this->form->getAttrib('load_ueditor')) :
        ?>
    	<script src="/libs/ueditor/ueditor.config.js" type="text/javascript"></script>
        <script src="/libs/ueditor/ueditor.all.min.js" type="text/javascript"></script>
        <script src="/libs/ueditor/ueditor.szkj.config.js" type="text/javascript"></script>
        <script type="text/javascript">
    	    <?php
            $editorIndex = 0;
            foreach ($this->form->getAttrib('ueditor_list') as $ueditor) :
                $ueditor = (object)$ueditor;
                $editorIndex ++;
            ?>
    	    var editor<?php echo $editorIndex ?> = new UE.ui.Editor(<?php echo $ueditor->toolbar == 'max' ? '' : 'szkj_ueditor_config' ?>);
    	    editor<?php echo $editorIndex ?>.render("<?php echo $ueditor->name ?>");
    	    <?php endforeach; ?>
    	</script>
    	<?php endif; ?>
    </body>
</html>
