<?php $this->headTitle('编辑页') ?>
<?php $this->headTitle('科室介绍') ?>
<?php $this->headLink()->appendStylesheet('/assets/admin/department-intro/edit.css') ?>
<?php $this->headScript()->appendFile('/assets/admin/department-intro/edit.js') ?>
<?php $this->headScript()->appendFile('/assets/admin/department-intro/validate-config.js') ?>

<div class="page-subheading page-subheading-md">
    <ol class="breadcrumb">
        <li><a href="javascript:;">控制面板</a></li>
        <li><a href="/admin/department-intro/manage">科室介绍管理</a></li>
        <li class="active"><a href="javascript:;">编辑</a></li>
    </ol>
</div>
<div class="page-heading page-heading-md">
    <h2>
        <i class="fa fa-edit"></i> 编辑科室介绍 
        <a href="javascript: history.go(-1)" class="btn btn-default pull-right">
    	    <i class="fa fa-chevron-left"></i> 返回</a>
    </h2>
</div>

<div class="container-fluid-md">
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h4 class="panel-title"><i class="fa fa-pencil"></i> 科室介绍</h4>

            <div class="panel-options">
            </div>
        </div>
        <div class="panel-body">
            <?php echo $this->form ?>
        </div>
    </div>
</div>