<?php $this->headTitle('医生介绍') ?>
<?php $this->headLink()->appendStylesheet('/assets/wx/website/doctor-detail.css?t=1') ?>
<div class="mui-content">
	<ul class="mui-table-view" id="mContent">
    	<li class="mui-table-view-cell mui-media">
        	<a href="/wx/website/list-detail/id/3">
            	<img class="mui-media-object mui-pull-left cover-image" src="/uploads/180329/dj.jpg">
            	<div class="mui-media-body">曾县中|主任医师
            	   <p>消化内科门诊</p>
            	</div>
        	</a>
    	</li>
	</ul>
	<ul class="mui-table-view2">
    	<li class="mui-table-view-cell mui-media shanchang">
        	擅长
    	</li>
    	<li class="mui-table-view-cell mui-media" style="border:none;">
        	<div class="intro">对神经科常见病、多发病，如脑血管病、周围神经病、颅内感染、癫痫、常见头痛、头晕等的诊断与治疗积累了丰富的临床经验。</div>
    	</li>
	</ul>
</div>