<?php $this->headTitle('医生介绍') ?>
<?php $this->headLink()->appendStylesheet('/assets/wx/website/doctor-list.css?t=1') ?>
<header class="mui-bar mui-bar-nav">
	<h1 class="mui-title">消化内科门诊共17名医生</h1>
</header>
<div class="mui-content">
	<ul class="mui-table-view" id="mContent">
    	<li class="mui-table-view-cell mui-media">
        	<a href="/wx/website/doctor-detail">
            	<img class="mui-media-object mui-pull-left cover-image" src="/uploads/180329/dj.jpg">
            	<div class="mui-media-body">曾县中|主任医师
            	   <p>消化内科门诊</p>
            	</div>
        	</a>
    	</li>
    	<li class="mui-table-view-cell mui-media">
        	<a href="/wx/website/doctor-detail">
            	<img class="mui-media-object mui-pull-left cover-image" src="/uploads/180329/dj.jpg">
            	<div class="mui-media-body">陈冠平|副主任医师
            	   <p>消化内科门诊</p>
            	</div>
        	</a>
    	</li>
    	<li class="mui-table-view-cell mui-media">
        	<a href="/wx/website/doctor-detail">
            	<img class="mui-media-object mui-pull-left cover-image" src="/uploads/180329/dj.jpg">
            	<div class="mui-media-body">张琦|副主任医师
            	   <p>消化内科门诊</p>
            	</div>
        	</a>
    	</li>
	</ul>
</div>