<?php $this->headTitle('首页') ?>
<?php $this->headLink()->appendStylesheet('/assets/wx/website/index.css') ?>
<?php $this->headLink()->appendStylesheet('/libs/mui/css/icons-extra.css') ?>
<div class="mui-navigate-rights">
	<img style="width:100%" src="/assets/wx/website/banner.jpg">
</div>
<div class="mui-content">
	<div class="mui-media-body">
		<ul class="mui-table-view mui-grid-view mui-grid-9">
    		<li class="mui-table-view-cell mui-media mui-col-xs-4 mui-col-sm-4">
    			<a href="/wx/website/detail">
    				<div class="img"><img src="/assets/wx/website/h.png"></div>
    				<div class="mui-media-body"><font>医院介绍</font></div>
    			</a>
    		</li>
    		<li class="mui-table-view-cell mui-media mui-col-xs-4 mui-col-sm-4">
    			<a href="/wx/department-intro/index">
    				<div class="img"><img src="/assets/wx/website/ys.png"></div>
    				<div class="mui-media-body"><font>科室介绍</font></div>
    			</a>
    		</li>
    		<li class="mui-table-view-cell mui-media mui-col-xs-4 mui-col-sm-4">
    			<a href="/wx/expert-intro/index">
    				<div class="img"><img src="/assets/wx/website/ys.png"></div>
    				<div class="mui-media-body"><font>专家介绍</font></div>
    			</a>
    		</li>
    		<li class="mui-table-view-cell mui-media mui-col-xs-4 mui-col-sm-4">
    			<a href="/wx/website/tower">
    				<div class="img"><img src="/assets/wx/website/w.png"></div>
    				<div class="mui-media-body"><font>楼群分布</font></div>
    			</a>
    		</li>
    		<li class="mui-table-view-cell mui-media mui-col-xs-4 mui-col-sm-4">
    			<a href="/wx/website/map">
    				<div class="img"><img src="/assets/wx/website/dh.png"></div>
    				<div class="mui-media-body"><font>来院导航</font></div>
    			</a>
    		</li>
    		<li class="mui-table-view-cell mui-media mui-col-xs-4 mui-col-sm-4">
    			<a href="/wx/website/list">
    				<div class="img"><img src="/assets/wx/website/dt.png"></div>
    				<div class="mui-media-body"><font>医院动态</font></div>
    			</a>
    		</li>
    	</ul>
    </div>
</div>