<?php $this->headTitle('管理列表页') ?>
<?php $this->headTitle('数据字典表') ?>
<link rel="stylesheet" type="text/css" href=""/>
<?php $this->headLink()->appendStylesheet('/libs/datatables/datatables.css') ?>
<?php $this->headScript()->appendFile('/libs/datatables/datatables.js') ?>

<?php $this->headScript()->appendFile('/assets/admin/common.manage.admin.szkj.js') ?>
<?php $this->headLink()->appendStylesheet('/assets/admin/dictionary/manage.css') ?>
<?php $this->headScript()->appendFile('/assets/admin/dictionary/manage.js?t='.time()) ?>

<div style="display: none">
    <input type="hidden" id="current_base_url" value="/admin/dictionary/manage" />
    <input type="hidden" id="ajax_delete_url" value="/admin/dictionary/delete" />
    <input type="hidden" id="columns-sort-serialized" value='<?php echo $this->columnsSortSerialized ?>' />
</div>

<div class="page-subheading page-subheading-md">
    <ol class="breadcrumb">
        <li><a href="javascript:;">控制面板</a></li>
        <li><a href="javascript:;">数据字典表管理</a></li>
        <li class="active"><a href="javascript:;">数据字典表列表</a></li>
    </ol>
</div>
<div class="page-heading page-heading-md">
    <h2>
        <i class="fa fa-gear"></i> 数据字典表管理 
        
        <span class="pull-right">
            <a href="/admin/dictionary/add" id="add_button" 
                szkj-resource="/admin/dictionary/add" 
                class="btn btn-primary szkj-acl"><i class="fa fa-plus"></i> 添加</a>
            <button id="edit_button" 
                szkj-resource="/admin/dictionary/edit" 
                class="btn btn-primary szkj-acl disabled"><i class="fa fa-pencil"></i> 编辑</button>
            <button id="view_button" 
                szkj-resource="/admin/dictionary/view" 
                class="btn btn-primary szkj-acl disabled"><i class="fa fa-eye"></i> 详情</button>
            <button id="delete_button" 
                szkj-resource="/admin/dictionary/delete" 
                class="btn btn-danger szkj-acl disabled"><i class="fa fa-trash-o"></i> 删除</button>
            <button id="toggle-search-panel" class="btn btn-primary">
                <i class="fa fa-search"></i> 查询</button>
            <a href="/admin/dictionary/import" id="import_button"
                szkj-resource="/admin/dictionary/import" 
                class="btn btn-primary szkj-acl"><i class="fa fa-cloud-upload"></i> 导入</a>
            <a href="/admin/dictionary/export" id="export_button"
                szkj-resource="/admin/dictionary/export" 
                class="btn btn-primary szkj-acl"><i class="fa fa-cloud-download"></i> 导出</a>
            <a href="/admin/dictionary/statistics" id="statistics_button"
                szkj-resource="/admin/dictionary/statistics" 
                class="btn btn-primary szkj-acl"><i class="fa fa-bar-chart-o"></i> 数据统计</a>
        </span>
    </h2>
</div>

<div class="container-fluid-md" style="display:none" id="search-panel">
    <div class="panel panel-primary panel-sm">
        <div class="panel-heading">
            <h4 class="panel-title"><i class="fa fa-search"></i> 查询</h4>
        </div>
        <div class="panel-body">
            <form class="form-inline" role="form" id="search_form">

				<div class="form-group">
					<label class="control-label" for="data_code_search">数据编码</label>
					<input type="text" class="form-control search-form-input" value="<?php echo $this->search_value_data_code ?>"
						name="data_code" id="data_code_search" placeholder="数据编码">
				</div>

				<div class="form-group">
					<label class="control-label" for="parent_code_search">父级编码</label>
					<input type="text" class="form-control search-form-input" value="<?php echo $this->search_value_parent_code ?>"
						name="parent_code" id="parent_code_search" placeholder="父级编码">
				</div>

				<div class="form-group">
					<label class="control-label" for="data_name_search">数据名称</label>
					<input type="text" class="form-control search-form-input" value="<?php echo $this->search_value_data_name ?>"
						name="data_name" id="data_name_search" placeholder="数据名称">
				</div>

                <button type="submit" class="btn btn-primary"><i class="fa fa-search"></i> 查询</button>
                <button type="button" class="btn btn-primary" id="search_form_reset_btn"><i class="fa fa-times"></i> 重置</button>
            </form>
        </div><!-- END panel-body -->
    </div><!-- END panel -->
</div><!-- END container-fluid-md -->

<div class="container-fluid-md">
    <div class="panel panel-default">
        <div class="panel-body">
            <table id="query-result-data-table" class="table table-bordered" cellspacing="0" width="100%">
                <thead>
                <tr>
                    <th data-column="data_code">数据编码</th>
                    <th data-column="parent_code">父级编码</th>
                    <th data-column="data_name">数据名称</th>
                </tr>
                </thead>
                <tbody>
            <?php if ($this->data): $counter = 1; foreach($this->data as $d):?>
                <tr data-id="<?php echo $d->id ?>">
					<td><?php echo $d->data_code ?></td>
					<td><?php echo $d->parent_code ?></td>
					<td><?php echo $d->data_name ?></td>
                </tr>
                <?php endforeach; endif; ?>
                </tbody>
            </table>
        </div>
    </div>
</div><!-- END container-fluid-md -->