<!doctype html>
<html class="no-js">
    <head>
        <!-- Meta, title, CSS, favicons, etc. -->
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="renderer" content="webkit|ie-comp|ie-stand">
        <title>临沂市人民医院服务窗 &middot; 登录 </title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width">
        <!--<link rel="shortcut icon" href="/favicon.ico">-->
        <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
        <link rel="stylesheet" href="/template/dist/css/bootstrap.min.css">
        <link rel="stylesheet" href="/template/dist/css/iriy-admin.min.css">
        <link rel="stylesheet" href="/template/demo/css/demo.css">
        <link rel="stylesheet" href="/template/dist/assets/font-awesome/css/font-awesome.css">
        <link rel="stylesheet" href="/assets/admin/auth/sign-in.css">
        <!--[if lt IE 9]>
        <script src="/template/dist/assets/libs/html5shiv/html5shiv.min.js"></script>
        <script src="/template/dist/assets/libs/respond/respond.min.js"></script>
        <![endif]-->

    </head>
    <body class="body-sign-in">
    <div class="container">
        <div class="panel panel-default form-container">
            <div class="panel-body">
                <form role="form" method="post">
                    <h3 class="text-center margin-xl-bottom">欢迎回来！</h3>

                    <div class="form-group text-center">
                        <label class="sr-only" for="email">用户名/手机号/邮箱地址</label>
                        <input type="text" class="form-control input-lg" 
                        	id="username" name="username" placeholder="用户名/手机号/邮箱地址">
                    </div>
                    <div class="form-group text-center">
                        <label class="sr-only" for="password">密码</label>
                        <input type="password" class="form-control input-lg" 
                        	id="password" name="password" placeholder="密码">
                    </div>

                    <button type="submit" class="btn btn-primary btn-block btn-lg"><i class="fa fa-user"></i> 登录</button>
                </form>
            </div>
            <div class="panel-body text-center">
                <div class="margin-bottom">
                    <a class="text-muted text-underline" href="javascript:;"><i class="fa fa-lock"></i> 忘记密码</a>
                </div>
                <div>
                    还没有账户？ <a class="text-primary-dark" href="/admin/auth/sign-up">立即注册</a>
                </div>
            </div>
        </div>
    </div>
</body>

</html>
