<?php $this->headTitle("支付失败")?>
<html>
	<head>
    	<meta charset="utf-8">
    	<meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=0">
        <link href="/libs/weui/dist/style/weui.min.css" rel="stylesheet">
        <link href="/libs/weui/dist/style/weui.css" rel="stylesheet">
        <link href="/libs/weui/dist/example/example.css" rel="stylesheet">
    </head>
    <body>
        <div class="page msg_success js_show">
            <div class="weui-msg">
                <div class="weui-msg__icon-area"><i class="weui-icon-warn weui-icon_msg"></i></div>
                <div class="weui-msg__text-area">
                    <h2 class="weui-msg__title">支付失败</h2>
                </div>
                <div class="weui-msg__opr-area">
                    <p class="weui-btn-area">
                        <a href="/wx/physician-service/index" class="weui-btn weui-btn_default">返回主界面</a>
                    </p>
                </div>
            </div>
        </div>
    </body>
</html>