<?php $this->headTitle('挂号成功') ?>
<?php $this->headLink()->appendStylesheet('/assets/wx/appointment/dzf.css') ?>
<?php //$this->headScript()->appendFile('/assets/wx/abouts/list.js') ?>
<style>
.weui-btn_default{
    width: 90%;
    font-size: 15px;
}
</style>
<div class="weui-panel__bd">
    <a href="javascript:void(0);" class="weui-media-box weui-media-box_appmsg">
        <div class="weui-media-box__hd">
            <i class="weui-icon-warn weui-icon_msg"></i>
        </div>
        <div class="weui-media-box__bd">
            <h4 class="weui-media-box__title">取消成功</h4>
            <p class="weui-media-box__desc">您已成功取消预约/挂号，如有疑问，请联系客服！</p>
        </div>
    </a>
</div>

<div class="page__bd">
    <div class="weui-form-preview">
        <div class="weui-form-preview__hd">
            <div class="weui-form-preview__item item">
                <label class="weui-form-preview__label">详细信息</label>
            </div>
        </div>
        <div class="weui-form-preview__bd">
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">就诊时段</label>
                <span class="weui-form-preview__value red">2018-02-12</span>
                <span class="weui-form-preview__value red">周二 上午8：00-9：00</span>
            </div>
        </div>
        <div class="weui-form-preview__bd">
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">费用类型</label>
                <span class="weui-form-preview__value black">预约挂号</span>
            </div>
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">医院名称</label>
                <span class="weui-form-preview__value">济南市立三院</span>
            </div>
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">就诊科室</label>
                <span class="weui-form-preview__value black">消化内科门诊</span>
            </div>
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">科室位置</label>
                <span class="weui-form-preview__value red">门诊二楼</span>
            </div>
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">医生姓名</label>
                <span class="weui-form-preview__value black">李弘基</span>
            </div>
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">医生职称</label>
                <span class="weui-form-preview__value">主任医师</span>
            </div>
        </div>
        <div class="weui-form-preview__bd">
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">就诊人</label>
                <span class="weui-form-preview__value">张三</span>
                <span class="weui-form-preview__value">无卡</span>
            </div>
        </div>
        <div class="weui-form-preview__bd">
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">医院单号</label>
                <span class="weui-form-preview__value black">201805112136483</span>
            </div>
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">平台单号</label>
                <span class="weui-form-preview__value black">1805110205500000677</span>
            </div>
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">交易金额</label>
                <span class="weui-form-preview__value black">￥24</span>
            </div>
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">支付状态</label>
                <span class="weui-form-preview__value">未支付</span>
            </div>
        </div>
        <div class="weui-form-preview__bd">
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">取消时间</label>
                <span class="weui-form-preview__value black">201-05-11 14：20：20</span>
            </div>
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">取消原因</label>
                <span class="weui-form-preview__value black">123</span>
            </div>
        </div>
    </div>
    
</div>