<!doctype html>
<html lang="zh">
<head>
<meta charset="utf-8">
<style type="text/css">
table td, table th {
	border: 1px solid #000;
}
</style>
</head>
<body>
	<table>
		<thead>
			<tr>
					<th>资源名称 resource_name</th>
					<th>用户名称 sys_user_name</th>
					<th>请求内容 request_data</th>
					<th>操作时间 log_time</th>
					<th>来源IP ip</th>

			</tr>
		</thead>
		<tbody>
            <?php if ($this->data): foreach($this->data as $d):?>
            <tr>
					<td style="mso-number-format='\@'"><?php echo $d->resource_name ?></td>
					<td style="mso-number-format='\@'"><?php echo $d->sys_user_name ?></td>
					<td style="mso-number-format='\@'"><?php echo $d->request_data ?></td>
					<td style="mso-number-format='\@'"><?php echo $d->log_time ?></td>
					<td style="mso-number-format='\@'"><?php echo $d->ip ?></td>
			</tr>
            <?php endforeach; endif; ?>
        </tbody>
	</table>
</body>
</html>
