<?php $this->headTitle('管理列表页') ?>
<?php $this->headTitle('系统操作日志') ?>
<link rel="stylesheet" type="text/css" href=""/>
<?php $this->headLink()->appendStylesheet('/libs/datatables/datatables.css') ?>
<?php $this->headScript()->appendFile('/libs/datatables/datatables.js') ?>

<?php $this->headScript()->appendFile('/assets/admin/common.manage.admin.szkj.js') ?>
<?php $this->headLink()->appendStylesheet('/assets/admin/xt-log/manage.css') ?>
<?php $this->headScript()->appendFile('/assets/admin/xt-log/manage.js?t='.time()) ?>

<div style="display: none">
    <input type="hidden" id="current_base_url" value="/admin/xt-log/manage" />
    <input type="hidden" id="ajax_delete_url" value="/admin/xt-log/delete" />
    <input type="hidden" id="columns-sort-serialized" value='<?php echo $this->columnsSortSerialized ?>' />
</div>

<div class="page-subheading page-subheading-md">
    <ol class="breadcrumb">
        <li><a href="javascript:;">控制面板</a></li>
        <li><a href="javascript:;">系统操作日志管理</a></li>
        <li class="active"><a href="javascript:;">系统操作日志列表</a></li>
    </ol>
</div>
<div class="page-heading page-heading-md">
    <h2>
        <i class="fa fa-gear"></i> 系统操作日志管理 
        
        <span class="pull-right">
            <a href="/admin/xt-log/add" id="add_button" 
                szkj-resource="/admin/xt-log/add" 
                class="btn btn-primary szkj-acl"><i class="fa fa-plus"></i> 添加</a>
            <button id="edit_button" 
                szkj-resource="/admin/xt-log/edit" 
                class="btn btn-primary szkj-acl disabled"><i class="fa fa-pencil"></i> 编辑</button>
            <button id="view_button" 
                szkj-resource="/admin/xt-log/view" 
                class="btn btn-primary szkj-acl disabled"><i class="fa fa-eye"></i> 详情</button>
            <button id="delete_button" 
                szkj-resource="/admin/xt-log/delete" 
                class="btn btn-danger szkj-acl disabled"><i class="fa fa-trash-o"></i> 删除</button>
            <button id="toggle-search-panel" class="btn btn-primary">
                <i class="fa fa-search"></i> 查询</button>
            <a href="/admin/xt-log/import" id="import_button"
                szkj-resource="/admin/xt-log/import" 
                class="btn btn-primary szkj-acl"><i class="fa fa-cloud-upload"></i> 导入</a>
            <a href="/admin/xt-log/export" id="export_button"
                szkj-resource="/admin/xt-log/export" 
                class="btn btn-primary szkj-acl"><i class="fa fa-cloud-download"></i> 导出</a>
            <a href="/admin/xt-log/statistics" id="statistics_button"
                szkj-resource="/admin/xt-log/statistics" 
                class="btn btn-primary szkj-acl"><i class="fa fa-bar-chart-o"></i> 数据统计</a>
        </span>
    </h2>
</div>

<div class="container-fluid-md" style="display:none" id="search-panel">
    <div class="panel panel-primary panel-sm">
        <div class="panel-heading">
            <h4 class="panel-title"><i class="fa fa-search"></i> 查询</h4>
        </div>
        <div class="panel-body">
            <form class="form-inline" role="form" id="search_form">

				<div class="form-group">
					<label class="control-label" for="resource_name_search">资源名称</label>
					<input type="text" class="form-control search-form-input" value="<?php echo $this->search_value_resource_name ?>"
						name="resource_name" id="resource_name_search" placeholder="资源名称">
				</div>

				<div class="form-group">
					<label class="control-label" for="sys_user_name_search">用户名称</label>
					<input type="text" class="form-control search-form-input" value="<?php echo $this->search_value_sys_user_name ?>"
						name="sys_user_name" id="sys_user_name_search" placeholder="用户名称">
				</div>

				<div class="form-group">
					<label class="control-label" for="request_data_search">请求内容</label>
					<input type="text" class="form-control search-form-input" value="<?php echo $this->search_value_request_data ?>"
						name="request_data" id="request_data_search" placeholder="请求内容">
				</div>

				<div class="form-group">
					<label class="control-label" for="log_time_search">操作时间</label>
					<input type="text" class="form-control search-form-input" value="<?php echo $this->search_value_log_time ?>"
						name="log_time" id="log_time_search" placeholder="操作时间">
				</div>

				<div class="form-group">
					<label class="control-label" for="ip_search">来源IP</label>
					<input type="text" class="form-control search-form-input" value="<?php echo $this->search_value_ip ?>"
						name="ip" id="ip_search" placeholder="来源IP">
				</div>

                <button type="submit" class="btn btn-primary"><i class="fa fa-search"></i> 查询</button>
                <button type="button" class="btn btn-primary" id="search_form_reset_btn"><i class="fa fa-times"></i> 重置</button>
            </form>
        </div><!-- END panel-body -->
    </div><!-- END panel -->
</div><!-- END container-fluid-md -->

<div class="container-fluid-md">
    <div class="panel panel-default">
        <div class="panel-body">
            <table id="query-result-data-table" class="table table-bordered" cellspacing="0" width="100%">
                <thead>
                <tr>
                    <th data-column="resource_name">资源名称</th>
                    <th data-column="sys_user_name">用户名称</th>
                    <th data-column="log_time">操作时间</th>
                    <th data-column="ip">来源IP</th>
                </tr>
                </thead>
                <tbody>
            <?php if ($this->data): $counter = 1; foreach($this->data as $d):?>
                <tr data-id="<?php echo $d->id ?>">
					<td><?php echo $d->resource_name ?></td>
					<td><?php echo $d->sys_user_name ?></td>
					<td><?php echo $d->log_time ?></td>
					<td><?php echo $d->ip ?></td>
                </tr>
                <?php endforeach; endif; ?>
                </tbody>
            </table>
        </div>
    </div>
</div><!-- END container-fluid-md -->