<?php $this->headTitle('查看页') ?>
<?php $this->headTitle('系统操作日志') ?>
<?php $this->headLink()->appendStylesheet('/assets/admin/xt-log/view.css') ?>
<?php $this->headScript()->appendFile('/assets/admin/xt-log/view.js') ?>

<?php $d = $this->data ?>

<div class="page-subheading page-subheading-md">
    <ol class="breadcrumb">
        <li><a href="javascript:;">控制面板</a></li>
        <li><a href="/admin/xt-log/manage">系统操作日志管理</a></li>
        <li class="active"><a href="javascript:;">查看</a></li>
    </ol>
</div>
<div class="page-heading page-heading-md">
    <h2>
        <i class="fa fa-info-circle"></i> 系统操作日志详情 
        <a href="javascript: history.go(-1)" class="btn btn-default pull-right">
    	    <i class="fa fa-chevron-left"></i> 返回</a>
    </h2>
</div>

<div class="container-fluid-md">
    <div class="panel panel-default">
        <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-striped table-bordered table-detail-view">
                    <tbody>
				<tr>
					<th>资源名称</th>
					<td><?php echo $d->resource_name ?></td>
				</tr>
				<tr>
					<th>用户名称</th>
					<td><?php echo $d->sys_user_name ?></td>
				</tr>
				<tr>
					<th>请求内容</th>
					<td><?php echo $d->request_data ?></td>
				</tr>
				<tr>
					<th>操作时间</th>
					<td><?php echo $d->log_time ?></td>
				</tr>
				<tr>
					<th>来源IP</th>
					<td><?php echo $d->ip ?></td>
				</tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>