<?php $this->headTitle('历史预约记录') ?>
<?php $this->headLink()->appendStylesheet('/assets/wx/report-query/index.css') ?>

<div class="weui-panel__bd">
    <a href="javascript:void(0);" class="weui-media-box weui-media-box_appmsg">
        <div class="weui-media-box__hd">
            <img src="/assets/wx/img/see.png" />
        </div>
        <div class="weui-media-box__bd">
            <h4 class="weui-media-box__title">预约记录</h4>
            <p class="weui-media-box__desc">以下是您最近两周内的预约记录：<br>"检验中的"报告出来后会发微信消息通知您。</p>
        </div>
    </a>
</div>

<div class="page__bd">
    <div class="weui-form-preview">
        <div class="weui-form-preview__hd">
            <div class="weui-form-preview__item item">
                <label class="weui-form-preview__label"><i class="fa fa-file-text-o"></i>&nbsp;血常规</label>
                <button type="reset" onclick="location.href='/wx/history/jz-record-detail'" class="weui-btn weui-btn_primary">查看详情</button>
            </div>
        </div>
        <div class="weui-form-preview__bd">
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">姓名</label>
                <span class="weui-form-preview__value">孙晓亮</span>
            </div>
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">送检日期</label>
                <span class="weui-form-preview__value">2018-01-25</span>
            </div>
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">状态</label>
                <span class="weui-form-preview__value status">结果已出</span>
            </div>
        </div>
    </div>
    <div class="weui-form-preview">
        <div class="weui-form-preview__hd">
            <div class="weui-form-preview__item item">
                <label class="weui-form-preview__label"><i class="fa fa-file-text-o"></i>&nbsp;血常规</label>
            </div>
        </div>
        <div class="weui-form-preview__bd">
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">姓名</label>
                <span class="weui-form-preview__value">孙晓亮</span>
            </div>
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">送检日期</label>
                <span class="weui-form-preview__value">2018-04-01</span>
            </div>
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">状态</label>
                <span class="weui-form-preview__value status">检验中</span>
            </div>
        </div>
    </div>
</div>