<?php $this->headTitle('管理列表页') ?>
<?php $this->headTitle('我的收藏') ?>
<link rel="stylesheet" type="text/css" href=""/>
<?php $this->headLink()->appendStylesheet('/libs/datatables/datatables.css') ?>
<?php $this->headScript()->appendFile('/libs/datatables/datatables.js') ?>

<?php $this->headScript()->appendFile('/assets/admin/common.manage.admin.szkj.js') ?>
<?php $this->headLink()->appendStylesheet('/assets/admin/collect/manage.css') ?>
<?php $this->headScript()->appendFile('/assets/admin/collect/manage.js?t='.time()) ?>

<div style="display: none">
    <input type="hidden" id="current_base_url" value="/admin/collect/manage" />
    <input type="hidden" id="ajax_delete_url" value="/admin/collect/delete" />
    <input type="hidden" id="columns-sort-serialized" value='<?php echo $this->columnsSortSerialized ?>' />
</div>

<div class="page-subheading page-subheading-md">
    <ol class="breadcrumb">
        <li><a href="javascript:;">控制面板</a></li>
        <li><a href="javascript:;">我的收藏管理</a></li>
        <li class="active"><a href="javascript:;">我的收藏列表</a></li>
    </ol>
</div>
<div class="page-heading page-heading-md">
    <h2>
        <i class="fa fa-gear"></i> 我的收藏管理 
        
        <span class="pull-right">
            <a href="/admin/collect/add" id="add_button" 
                szkj-resource="/admin/collect/add" 
                class="btn btn-primary szkj-acl"><i class="fa fa-plus"></i> 添加</a>
            <button id="edit_button" 
                szkj-resource="/admin/collect/edit" 
                class="btn btn-primary szkj-acl disabled"><i class="fa fa-pencil"></i> 编辑</button>
            <button id="view_button" 
                szkj-resource="/admin/collect/view" 
                class="btn btn-primary szkj-acl disabled"><i class="fa fa-eye"></i> 详情</button>
            <button id="delete_button" 
                szkj-resource="/admin/collect/delete" 
                class="btn btn-danger szkj-acl disabled"><i class="fa fa-trash-o"></i> 删除</button>
            <button id="toggle-search-panel" class="btn btn-primary">
                <i class="fa fa-search"></i> 查询</button>
            <a href="/admin/collect/import" id="import_button"
                szkj-resource="/admin/collect/import" 
                class="btn btn-primary szkj-acl"><i class="fa fa-cloud-upload"></i> 导入</a>
            <a href="/admin/collect/export" id="export_button"
                szkj-resource="/admin/collect/export" 
                class="btn btn-primary szkj-acl"><i class="fa fa-cloud-download"></i> 导出</a>
            <a href="/admin/collect/statistics" id="statistics_button"
                szkj-resource="/admin/collect/statistics" 
                class="btn btn-primary szkj-acl"><i class="fa fa-bar-chart-o"></i> 数据统计</a>
        </span>
    </h2>
</div>

<div class="container-fluid-md" style="display:none" id="search-panel">
    <div class="panel panel-primary panel-sm">
        <div class="panel-heading">
            <h4 class="panel-title"><i class="fa fa-search"></i> 查询</h4>
        </div>
        <div class="panel-body">
            <form class="form-inline" role="form" id="search_form">

				<div class="form-group">
					<label class="control-label" for="openid_search">openid</label>
					<input type="text" class="form-control search-form-input" value="<?php echo $this->search_value_openid ?>"
						name="openid" id="openid_search" placeholder="openid">
				</div>

				<div class="form-group">
					<label class="control-label" for="doctor_name_search">医生姓名</label>
					<input type="text" class="form-control search-form-input" value="<?php echo $this->search_value_doctor_name ?>"
						name="doctor_name" id="doctor_name_search" placeholder="医生姓名">
				</div>

				<div class="form-group">
					<label class="control-label" for="doctor_call_search">医生职称</label>
					<input type="text" class="form-control search-form-input" value="<?php echo $this->search_value_doctor_call ?>"
						name="doctor_call" id="doctor_call_search" placeholder="医生职称">
				</div>

				<div class="form-group">
					<label class="control-label" for="department_search">所在科室</label>
					<input type="text" class="form-control search-form-input" value="<?php echo $this->search_value_department ?>"
						name="department" id="department_search" placeholder="所在科室">
				</div>

				<div class="form-group">
					<label class="control-label" for="date_search">日期</label>
					<input type="text" class="form-control search-form-input" value="<?php echo $this->search_value_date ?>"
						name="date" id="date_search" placeholder="日期">
				</div>

                <button type="submit" class="btn btn-primary"><i class="fa fa-search"></i> 查询</button>
                <button type="button" class="btn btn-primary" id="search_form_reset_btn"><i class="fa fa-times"></i> 重置</button>
            </form>
        </div><!-- END panel-body -->
    </div><!-- END panel -->
</div><!-- END container-fluid-md -->

<div class="container-fluid-md">
    <div class="panel panel-default">
        <div class="panel-body">
            <table id="query-result-data-table" class="table table-bordered" cellspacing="0" width="100%">
                <thead>
                <tr>
                    <th data-column="openid">openid</th>
                    <th data-column="doctor_name">医生姓名</th>
                    <th data-column="doctor_call">医生职称</th>
                    <th data-column="department">所在科室</th>
                    <th data-column="date">日期</th>
                </tr>
                </thead>
                <tbody>
            <?php if ($this->data): $counter = 1; foreach($this->data as $d):?>
                <tr data-id="<?php echo $d->id ?>">
					<td><?php echo $d->openid ?></td>
					<td><?php echo $d->doctor_name ?></td>
					<td><?php echo $d->doctor_call ?></td>
					<td><?php echo $d->department ?></td>
					<td><?php echo $d->date ? date("Y-m-d H:i:s", strtotime($d->date)) : "" ?></td>
                </tr>
                <?php endforeach; endif; ?>
                </tbody>
            </table>
        </div>
    </div>
</div><!-- END container-fluid-md -->