<?php $this->headTitle('数据统计') ?>
<?php $this->headTitle('我的收藏') ?>
<?php $this->headLink()->appendStylesheet('/template/dist/css/plugins/jquery-dataTables.min.css') ?>
<?php $this->headScript()->appendFile('/template/dist/assets/plugins/jquery-datatables/js/jquery.dataTables.js') ?>
<?php $this->headScript()->appendFile('/template/dist/assets/plugins/jquery-datatables/js/dataTables.tableTools.js') ?>
<?php $this->headScript()->appendFile('/template/dist/assets/plugins/jquery-datatables/js/dataTables.bootstrap.js') ?>
<?php //$this->headScript()->appendFile('http://cdn.hcharts.cn/highcharts/highcharts.js') ?>
<?php //$this->headScript()->appendFile('http://cdn.hcharts.cn/highcharts/modules/exporting.js') ?>
<?php $this->headLink()->appendStylesheet('/assets/admin/collect/statistics.css') ?>
<?php $this->headScript()->appendFile('/assets/admin/collect/statistics.js') ?>

<div class="page-subheading page-subheading-md">
    <ol class="breadcrumb">
        <li><a href="javascript:;">控制面板</a></li>
        <li><a href="/admin/collect/manage">我的收藏管理</a></li>
        <li class="active"><a href="javascript:;">数据统计</a></li>
    </ol>
</div>
<div class="page-heading page-heading-md">
    <h2>
        <i class="fa fa-bar-chart-o"></i> 我的收藏数据统计 
        <a href="javascript: history.go(-1)" class="btn btn-default pull-right">
    	    <i class="fa fa-chevron-left"></i> 返回</a>
    </h2>
</div>

<div class="container-fluid-md">
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h4 class="panel-title"><i class="fa fa-fw fa-bar-chart-o"></i> 数据占比统计</h4>

            <div class="panel-options">
            </div>
        </div>
        <ul class="nav nav-tabs">
			<li class="active"><a data-toggle="tab" href="#tab-openid">openid</a></li>
			<li><a data-toggle="tab" href="#tab-doctor-name">医生姓名</a></li>
			<li><a data-toggle="tab" href="#tab-doctor-call">医生职称</a></li>
			<li><a data-toggle="tab" href="#tab-department">所在科室</a></li>
			<li><a data-toggle="tab" href="#tab-date">日期</a></li>

        </ul>
        <div class="tab-content">
			<div id="tab-openid" class="tab-pane active">
                <table class="table table-striped datatable">
                    <thead>
                    <tr>
                        <th>openid</th>
                        <th>数量</th>
                        <th>占比</th>
                        <th>&nbsp;</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php if ($this->dataOpenid): 
                    foreach ($this->dataOpenid as $d): 
                        $percent = sprintf('%.2f', 100 * $d->count / $this->totalRowsCount);
                    ?>
                    <tr>
                        <td><?php echo $d->openid ?></td>
                        <td><?php echo $d->count ?></td>
                        <td><?php echo $percent ?>%</td>
                        <td>
                            <div class="progress progress-xs">
                                <div class="progress-bar" role="progressbar" 
                                    aria-valuenow="<?php echo $percent ?>" aria-valuemin="0" 
                                    aria-valuemax="100" style="width: <?php echo $percent ?>%;">
                                    <span class="sr-only"><?php echo $percent ?>%</span>
                                </div>
                            </div>
                        </td>
                    </tr>
                    <?php endforeach; endif; ?>
                    </tbody>
                    <tfoot>
                    </tfoot>
                </table>
            </div>
			<div id="tab-doctor-name" class="tab-pane">
                <table class="table table-striped datatable">
                    <thead>
                    <tr>
                        <th>医生姓名</th>
                        <th>数量</th>
                        <th>占比</th>
                        <th>&nbsp;</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php if ($this->dataDoctorName): 
                    foreach ($this->dataDoctorName as $d): 
                        $percent = sprintf('%.2f', 100 * $d->count / $this->totalRowsCount);
                    ?>
                    <tr>
                        <td><?php echo $d->doctor_name ?></td>
                        <td><?php echo $d->count ?></td>
                        <td><?php echo $percent ?>%</td>
                        <td>
                            <div class="progress progress-xs">
                                <div class="progress-bar" role="progressbar" 
                                    aria-valuenow="<?php echo $percent ?>" aria-valuemin="0" 
                                    aria-valuemax="100" style="width: <?php echo $percent ?>%;">
                                    <span class="sr-only"><?php echo $percent ?>%</span>
                                </div>
                            </div>
                        </td>
                    </tr>
                    <?php endforeach; endif; ?>
                    </tbody>
                    <tfoot>
                    </tfoot>
                </table>
            </div>
			<div id="tab-doctor-call" class="tab-pane">
                <table class="table table-striped datatable">
                    <thead>
                    <tr>
                        <th>医生职称</th>
                        <th>数量</th>
                        <th>占比</th>
                        <th>&nbsp;</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php if ($this->dataDoctorCall): 
                    foreach ($this->dataDoctorCall as $d): 
                        $percent = sprintf('%.2f', 100 * $d->count / $this->totalRowsCount);
                    ?>
                    <tr>
                        <td><?php echo $d->doctor_call ?></td>
                        <td><?php echo $d->count ?></td>
                        <td><?php echo $percent ?>%</td>
                        <td>
                            <div class="progress progress-xs">
                                <div class="progress-bar" role="progressbar" 
                                    aria-valuenow="<?php echo $percent ?>" aria-valuemin="0" 
                                    aria-valuemax="100" style="width: <?php echo $percent ?>%;">
                                    <span class="sr-only"><?php echo $percent ?>%</span>
                                </div>
                            </div>
                        </td>
                    </tr>
                    <?php endforeach; endif; ?>
                    </tbody>
                    <tfoot>
                    </tfoot>
                </table>
            </div>
			<div id="tab-department" class="tab-pane">
                <table class="table table-striped datatable">
                    <thead>
                    <tr>
                        <th>所在科室</th>
                        <th>数量</th>
                        <th>占比</th>
                        <th>&nbsp;</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php if ($this->dataDepartment): 
                    foreach ($this->dataDepartment as $d): 
                        $percent = sprintf('%.2f', 100 * $d->count / $this->totalRowsCount);
                    ?>
                    <tr>
                        <td><?php echo $d->department ?></td>
                        <td><?php echo $d->count ?></td>
                        <td><?php echo $percent ?>%</td>
                        <td>
                            <div class="progress progress-xs">
                                <div class="progress-bar" role="progressbar" 
                                    aria-valuenow="<?php echo $percent ?>" aria-valuemin="0" 
                                    aria-valuemax="100" style="width: <?php echo $percent ?>%;">
                                    <span class="sr-only"><?php echo $percent ?>%</span>
                                </div>
                            </div>
                        </td>
                    </tr>
                    <?php endforeach; endif; ?>
                    </tbody>
                    <tfoot>
                    </tfoot>
                </table>
            </div>
			<div id="tab-date" class="tab-pane">
                <table class="table table-striped datatable">
                    <thead>
                    <tr>
                        <th>日期</th>
                        <th>数量</th>
                        <th>占比</th>
                        <th>&nbsp;</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php if ($this->dataDate): 
                    foreach ($this->dataDate as $d): 
                        $percent = sprintf('%.2f', 100 * $d->count / $this->totalRowsCount);
                    ?>
                    <tr>
                        <td><?php echo $d->date ?></td>
                        <td><?php echo $d->count ?></td>
                        <td><?php echo $percent ?>%</td>
                        <td>
                            <div class="progress progress-xs">
                                <div class="progress-bar" role="progressbar" 
                                    aria-valuenow="<?php echo $percent ?>" aria-valuemin="0" 
                                    aria-valuemax="100" style="width: <?php echo $percent ?>%;">
                                    <span class="sr-only"><?php echo $percent ?>%</span>
                                </div>
                            </div>
                        </td>
                    </tr>
                    <?php endforeach; endif; ?>
                    </tbody>
                    <tfoot>
                    </tfoot>
                </table>
            </div>

        </div>
    </div>
</div>