<?php $this->headTitle('查看页') ?>
<?php $this->headTitle('住院查询') ?>
<?php $this->headLink()->appendStylesheet('/assets/admin/hospitalized-select/view.css') ?>
<?php $this->headScript()->appendFile('/assets/admin/hospitalized-select/view.js') ?>

<?php $d = $this->data ?>

<div class="page-subheading page-subheading-md">
    <ol class="breadcrumb">
        <li><a href="javascript:;">控制面板</a></li>
        <li><a href="/admin/hospitalized-select/manage">住院查询管理</a></li>
        <li class="active"><a href="javascript:;">查看</a></li>
    </ol>
</div>
<div class="page-heading page-heading-md">
    <h2>
        <i class="fa fa-info-circle"></i> 住院查询详情 
        <a href="javascript: history.go(-1)" class="btn btn-default pull-right">
    	    <i class="fa fa-chevron-left"></i> 返回</a>
    </h2>
</div>

<div class="container-fluid-md">
    <div class="panel panel-default">
        <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-striped table-bordered table-detail-view">
                    <tbody>
				<tr>
					<th>姓名</th>
					<td><?php echo $d->name ?></td>
				</tr>
				<tr>
					<th>身份证号</th>
					<td><?php echo $d->card_no ?></td>
				</tr>
				<tr>
					<th>日期</th>
					<td><?php echo $d->date ?></td>
				</tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>