<!doctype html>
<html lang="zh">
<head>
<meta charset="utf-8">
<style type="text/css">
table td, table th {
	border: 1px solid #000;
}
</style>
</head>
<body>
	<table>
		<thead>
			<tr>
					<th>轮播图 thumb</th>

			</tr>
		</thead>
		<tbody>
            <?php if ($this->data): foreach($this->data as $d):?>
            <tr>
					<td style="mso-number-format='\@'">
                    <?php if ($d->thumb): ?>
                    <?php echo "http://".$_SERVER["HTTP_HOST"].$d->thumb ?>
                    <?php endif; ?>
					</td>
			</tr>
            <?php endforeach; endif; ?>
        </tbody>
	</table>
</body>
</html>
