<?php $this->headTitle('管理列表页') ?>
<?php $this->headTitle('轮播图') ?>
<link rel="stylesheet" type="text/css" href=""/>
<?php $this->headLink()->appendStylesheet('/libs/datatables/datatables.css') ?>
<?php $this->headScript()->appendFile('/libs/datatables/datatables.js') ?>

<?php $this->headScript()->appendFile('/assets/admin/common.manage.admin.szkj.js') ?>
<?php $this->headLink()->appendStylesheet('/assets/admin/slides/manage.css') ?>
<?php $this->headScript()->appendFile('/assets/admin/slides/manage.js?t='.time()) ?>

<div style="display: none">
    <input type="hidden" id="current_base_url" value="/admin/slides/manage" />
    <input type="hidden" id="ajax_delete_url" value="/admin/slides/delete" />
    <input type="hidden" id="columns-sort-serialized" value='<?php echo $this->columnsSortSerialized ?>' />
</div>

<div class="page-subheading page-subheading-md">
    <ol class="breadcrumb">
        <li><a href="javascript:;">控制面板</a></li>
        <li><a href="javascript:;">轮播图管理</a></li>
        <li class="active"><a href="javascript:;">轮播图列表</a></li>
    </ol>
</div>
<div class="page-heading page-heading-md">
    <h2>
        <i class="fa fa-gear"></i> 轮播图管理 
        
        <span class="pull-right">
            <a href="/admin/slides/add" id="add_button" 
                szkj-resource="/admin/slides/add" 
                class="btn btn-primary szkj-acl"><i class="fa fa-plus"></i> 添加</a>
            <button id="edit_button" 
                szkj-resource="/admin/slides/edit" 
                class="btn btn-primary szkj-acl disabled"><i class="fa fa-pencil"></i> 编辑</button>
            <button id="view_button" 
                szkj-resource="/admin/slides/view" 
                class="btn btn-primary szkj-acl disabled"><i class="fa fa-eye"></i> 详情</button>
            <button id="delete_button" 
                szkj-resource="/admin/slides/delete" 
                class="btn btn-danger szkj-acl disabled"><i class="fa fa-trash-o"></i> 删除</button>
            <button id="toggle-search-panel" class="btn btn-primary">
                <i class="fa fa-search"></i> 查询</button>
            <a href="/admin/slides/import" id="import_button"
                szkj-resource="/admin/slides/import" 
                class="btn btn-primary szkj-acl"><i class="fa fa-cloud-upload"></i> 导入</a>
            <a href="/admin/slides/export" id="export_button"
                szkj-resource="/admin/slides/export" 
                class="btn btn-primary szkj-acl"><i class="fa fa-cloud-download"></i> 导出</a>
            <a href="/admin/slides/statistics" id="statistics_button"
                szkj-resource="/admin/slides/statistics" 
                class="btn btn-primary szkj-acl"><i class="fa fa-bar-chart-o"></i> 数据统计</a>
        </span>
    </h2>
</div>

<div class="container-fluid-md" style="display:none" id="search-panel">
    <div class="panel panel-primary panel-sm">
        <div class="panel-heading">
            <h4 class="panel-title"><i class="fa fa-search"></i> 查询</h4>
        </div>
        <div class="panel-body">
            <form class="form-inline" role="form" id="search_form">

                <button type="submit" class="btn btn-primary"><i class="fa fa-search"></i> 查询</button>
                <button type="button" class="btn btn-primary" id="search_form_reset_btn"><i class="fa fa-times"></i> 重置</button>
            </form>
        </div><!-- END panel-body -->
    </div><!-- END panel -->
</div><!-- END container-fluid-md -->

<div class="container-fluid-md">
    <div class="panel panel-default">
        <div class="panel-body">
            <table id="query-result-data-table" class="table table-bordered" cellspacing="0" width="100%">
                <thead>
                <tr>
					<th>轮播图</th>
                </tr>
                </thead>
                <tbody>
            <?php if ($this->data): $counter = 1; foreach($this->data as $d):?>
                <tr data-id="<?php echo $d->id ?>">
					<td>
                    <?php if ($d->thumb): ?>
                    <a href="<?php echo $d->thumb ?>" target="_blank">
                        <img src="<?php echo Szkj_Helper_Thumb::getSpecifiedThumb($d->thumb, "s") ?>" class="thumbnail" style="max-height:80px" />
                    </a>
                    <?php endif; ?>
					</td>
                </tr>
                <?php endforeach; endif; ?>
                </tbody>
            </table>
        </div>
    </div>
</div><!-- END container-fluid-md -->