<?php $this->headTitle('详情页') ?>
<?php $this->headTitle('数据字典表') ?>
<?php $this->headLink()->appendStylesheet('/assets/default/dictionary/detail.css') ?>
<?php $this->headScript()->appendFile('/assets/default/dictionary/detail.js') ?>

<?php $d = $this->data ?>

<div class="container" style="margin-top:40px">
    
    <div class="row">
    
        <div class="col-lg-9 col-lg-9 col-sm-12 col-xs-12">
        
            <div class="page-header">
              <h1>数据字典表详情页 <small>Detail of Dictionary</small></h1>
            </div>
        
            <table class="table table-hover table-bordered table-rounded table-striped">
				<tr>
					<th>数据ID</th>
					<td><?php echo $d->id ?></td>
				</tr>
				<tr>
					<th>数据编码</th>
					<td><?php echo $d->data_code ?></td>
				</tr>
				<tr>
					<th>父级编码</th>
					<td><?php echo $d->parent_code ?></td>
				</tr>
				<tr>
					<th>数据名称</th>
					<td><?php echo $d->data_name ?></td>
				</tr>
            </table>
        
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">[面板模板]</h3>
                </div>
                <div class="panel-body">
                    ［面板内容面板内容面板内容面板内容面板内容面板内容面板内容面板内容面板内容面板内容面板内容］
                </div>
            </div>
        
        </div>
        
        
        <div class="col-lg-3 col-lg-3 col-sm-12 col-xs-12">
            <div class="list-group">
                <a href="#" class="list-group-item active">其它数据字典表</a>
                <?php if ($this->topData): foreach ($this->topData as $t): ?>
                <a href="/dictionary/detail/id/<?php echo $t->id ?>" class="list-group-item">数据字典表<?php echo $t->id ?></a>
                <?php endforeach; endif; ?>
            </div>
            
        </div>
    
    </div>

</div>