<?php $this->headTitle('医技预约') ?>
<?php $this->headLink()->appendStylesheet('/assets/wx/booking/index.css') ?>
<?php //$this->headScript()->appendFile('/assets/wx/abouts/list.js') ?>

<div class="weui-flex">
    <div class="weui-flex__item"><div class="placeholder">09-02<p>星期一</p></div></div>
    <div class="weui-flex__item"><div class="placeholder active">09-03<br><span>星期二</span></div></div>
    <div class="weui-flex__item"><div class="placeholder">09-04<p>星期三</p></div></div>
    <div class="weui-flex__item"><div class="placeholder">09-05<p>星期四</p></div></div>
    <div class="weui-flex__item"><div class="placeholder">09-06<p>星期五</p></div></div>
    <div class="weui-flex__item"><div class="placeholder">09-07<p>星期六</p></div></div>
    <div class="weui-flex__item"><div class="placeholder">09-08<p>星期日  </p></div></div>
</div>

<div class="page__bd">
    <div class="weui-form-preview">
        <div class="weui-form-preview__hd">
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">CT</label>
                <span class="weui-form-preview__value">CT颅内平扫（横断）</span>
            </div>
        </div>
        <div class="weui-form-preview__bd">
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">CT--1</label>
                <span class="weui-form-preview__value">2018-02-12</span>
            </div>
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">CT--2</label>
                <span class="weui-form-preview__value"></span>
            </div>
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">CT--3</label>
                <span class="weui-form-preview__value"></span>
            </div>
        </div>
    </div>
    <div class="weui-form-preview">
        <div class="weui-form-preview__hd">
            <div class="weui-form-preview__item item">
                <label class="weui-form-preview__label">多普勒超声检查</label>
                <span class="weui-form-preview__value">常规心脏超声检测</span>
            </div>
        </div>
        <div class="weui-form-preview__bd">
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">多普勒超声检查--1</label>
                <span class="weui-form-preview__value">15:00-17:00</span>
            </div>
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">多普勒超声检查--2</label>
                <span class="weui-form-preview__value"></span>
            </div>
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">多普勒超声检查--3</label>
                <span class="weui-form-preview__value"></span>
            </div>
        </div>
    </div>
    <div class="weui-form-preview">
        <div class="weui-form-preview__hd">
            <div class="weui-form-preview__item item">
                <label class="weui-form-preview__label">DR</label>
                <span class="weui-form-preview__value">DR腰椎正侧位片</span>
            </div>
        </div>
        <div class="weui-form-preview__bd">
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">DR--1</label>
                <span class="weui-form-preview__value">15:00-17:00</span>
            </div>
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">DR--2</label>
                <span class="weui-form-preview__value"></span>
            </div>
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">DR--3</label>
                <span class="weui-form-preview__value"></span>
            </div>
        </div>
    </div>
    <div class="weui-form-preview">
        <div class="weui-form-preview__hd">
            <div class="weui-form-preview__item item">
                <label class="weui-form-preview__label">DR</label>
                <span class="weui-form-preview__value">DR腰椎正侧位片</span>
            </div>
        </div>
        <div class="weui-form-preview__bd">
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">DR--1</label>
                <span class="weui-form-preview__value">15:00-17:00</span>
            </div>
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">DR--2</label>
                <span class="weui-form-preview__value"></span>
            </div>
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">DR--3</label>
                <span class="weui-form-preview__value"></span>
            </div>
        </div>
    </div>
</div>
<div class="weui-tabbar">
    <a href="/wx/booking/affirm" class="weui-btn weui-btn_primary">确认预约</a>
</div>