<?php $this->headTitle('我的医技预约') ?>
<?php $this->headLink()->appendStylesheet('/assets/wx/booking/list.css?t='.time()) ?>
<?php //$this->headScript()->appendFile('/assets/wx/abouts/list.js') ?>

<div class="page badge js_show">
    <div class="page__bd">
        <div class="weui-cells__title">选择就诊人</div>
        <div class="weui-cells">
            <div class="weui-cell">
                <div class="weui-cell__bd">
                    <label class="weui-form-preview__label"><i class="gi gi-user"></i>&nbsp;张三</label><br>
                    <p class="card">身份证：&emsp;124516196512154587</p>
                    <p class="jzk"> 就诊卡：&emsp;123456789</p>
                </div>
            </div>
        </div>
        <div class="weui-form-preview">
            <div class="weui-form-preview__hd">
                <div class="weui-form-preview__item item">
                    <label class="weui-form-preview__label wait"><i class="fa fa-check-square-o"></i> 已预约</label>
                    <a href="/wx/booking/sub-apply" class="weui-btn weui-btn_primary">查看详情</a>
                </div>
            </div>
            <div class="weui-form-preview__bd main">
                <div class="weui-form-preview__item">
                    <label class="weui-form-preview__label">就诊人:</label>
                    <span class="weui-form-preview__value">孙晓亮</span>
                </div>
                <div class="weui-form-preview__item">
                    <label class="weui-form-preview__label">预约项目:</label>
                    <span class="weui-form-preview__value">CT颅内平扫</span>
                </div>
                <div class="weui-form-preview__item">
                    <label class="weui-form-preview__label">接收科室:</label>
                    <span class="weui-form-preview__value">放射科/彩超室</span>
                </div>
                <div class="weui-form-preview__item">
                    <label class="weui-form-preview__label">金额总计:</label>
                    <span class="weui-form-preview__value price">2019元</span>
                </div>
            </div>
        </div>
        <div class="weui-form-preview">
            <div class="weui-form-preview__hd">
                <div class="weui-form-preview__item item">
                    <label class="weui-form-preview__label wait"><i class="fa fa-check-square-o"></i> 已预约</label>
                    <a href="/wx/booking/success" class="weui-btn weui-btn_primary">查看详情</a>
                </div>
            </div>
            <div class="weui-form-preview__bd main">
                <div class="weui-form-preview__item">
                    <label class="weui-form-preview__label">就诊人:</label>
                    <span class="weui-form-preview__value">孙晓亮</span>
                </div>
                <div class="weui-form-preview__item">
                    <label class="weui-form-preview__label">预约项目:</label>
                    <span class="weui-form-preview__value">CT颅内平扫</span>
                </div>
                <div class="weui-form-preview__item">
                    <label class="weui-form-preview__label">接收科室:</label>
                    <span class="weui-form-preview__value">放射科/彩超室</span>
                </div>
                <div class="weui-form-preview__item">
                    <label class="weui-form-preview__label">金额总计:</label>
                    <span class="weui-form-preview__value price">2019元</span>
                </div>
            </div>
        </div>
        <div class="weui-form-preview">
            <div class="weui-form-preview__hd">
                <div class="weui-form-preview__item item">
                    <label class="weui-form-preview__label no-wait"><i class="fa fa-check-square-o"></i> 已取消</label>
                    <a href="/wx/booking/cancel" class="weui-btn weui-btn_primary">查看详情</a>
                </div>
            </div> 
            <div class="weui-form-preview__bd main">
                <div class="weui-form-preview__item">
                    <label class="weui-form-preview__label">就诊人:</label>
                    <span class="weui-form-preview__value">孙晓亮</span>
                </div>
                <div class="weui-form-preview__item">
                    <label class="weui-form-preview__label">预约项目:</label>
                    <span class="weui-form-preview__value">CT颅内平扫</span>
                </div>
                <div class="weui-form-preview__item">
                    <label class="weui-form-preview__label">接收科室:</label>
                    <span class="weui-form-preview__value">放射科/彩超室</span>
                </div>
                <div class="weui-form-preview__item">
                    <label class="weui-form-preview__label">金额总计:</label>
                    <span class="weui-form-preview__value price">2019元</span>
                </div>
            </div>
        </div>
    </div>
</div>
