<?php $this->headTitle('已成功') ?>
<?php $this->headLink()->appendStylesheet('/assets/wx/booking/sub-apply.css') ?>
<?php //$this->headScript()->appendFile('/assets/wx/abouts/list.js') ?>

<div class="weui-panel__bd">
    <a href="javascript:void(0);" class="weui-media-box weui-media-box_appmsg">
        <div class="weui-media-box__hd">
            <i class="weui-icon-success weui-icon_msg"></i>
        </div>
        <div class="weui-media-box__bd">
            <h3 class="weui-media-box__title">医技预约申请已成功</h3>
            <p class="weui-media-box__desc">请您按时前去相应科室检查！</p>
        </div>
    </a>
</div>

<div class="page__bd">
    <div class="weui-form-preview">
        <div class="weui-form-preview__hd">
            <div class="weui-form-preview__item item">
                <label class="weui-form-preview__label"><i class="gi gi-user"></i>&nbsp;张三</label></label>
            </div>
        </div>
        <div class="weui-form-preview__bd">
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">核磁共振</label>
                <span class="weui-form-preview__value text-left">放射科  </span>
            </div>
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">预约时间：02-18 14:30</label>
                <span class="weui-form-preview__value red">￥996</span>
            </div>
        </div>
        <div class="weui-form-preview__bd">
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">彩超</label>
                <span class="weui-form-preview__value text-left">彩超室  </span>
            </div>
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">预约时间：02-18 14:30</label>
                <span class="weui-form-preview__value red">￥119</span>
            </div>
        </div>
        <div class="weui-form-preview__bd">
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">DR</label>
                <span class="weui-form-preview__value text-left">DR检测室  </span>
            </div>
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">预约时间：02-18 14:30</label>
                <span class="weui-form-preview__value red">￥119</span>
            </div>
        </div>
    </div>
    <div class="weui-form-preview">
        <div class="weui-form-preview__hd">
            <div class="weui-form-preview__item border-left">
                <label class="weui-form-preview__label" > 详细信息</label>
            </div>
        </div>
        <div class="weui-form-preview__bd">
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">订单状态</label>
                <span class="weui-form-preview__value">已支付  </span>
            </div>
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">提交时间</label>
                <span class="weui-form-preview__value">2018-02-25 10:01:25 </span>
            </div>
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">申请单号</label>
                <span class="weui-form-preview__value">134667896416545  </span>
            </div>
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">合计金额</label>
                <span class="weui-form-preview__value red total">￥1996元</span>
            </div>
        </div>
    </div>
</div>