<?php $this->headTitle('报告详情') ?>
<?php $this->headLink()->appendStylesheet('/assets/wx/report-query/detail.css') ?>
<div class="page__bd">
    <div class="weui-form-preview">
        <div class="weui-form-preview__hd">
            <div class="weui-form-preview__item item">
                <label class="weui-form-preview__label"><i class="fa fa-file-text-o"></i>&nbsp;血常规</label>
            </div>
        </div>
        <div class="weui-form-preview__bd main" style="height:112px">
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">姓名:</label>
                <span class="weui-form-preview__value">孙晓亮</span>
            </div>
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">年龄:</label>
                <span class="weui-form-preview__value">14</span>
            </div>
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">性别:</label>
                <span class="weui-form-preview__value">男</span>
            </div>
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">送检日期:</label>
                <span class="weui-form-preview__value">2018-01-25</span>
            </div>
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">样品:</label>
                <span class="weui-form-preview__value">血</span>
            </div>
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">&nbsp;</label>
                <span class="weui-form-preview__value">&nbsp;</span>
            </div>
        </div>
    </div>
</div>
<div class="page__ft">
    <div class="weui-form-preview">
        <div class="weui-form-preview__hd">
            <div class="weui-form-preview__item" style="margin-left:5px;">
                <label class="weui-form-preview__label">报告结果</label>
            </div>
        </div>
        <div class="weui-form-preview__bd">
        defwesfwefwefgwrfwesvfsdvggs
        </div>
    </div>
</div>