<?php $this->headTitle('报告详情') ?>
<?php $this->headLink()->appendStylesheet('/assets/wx/report-query/jyd-detail.css?t='.time()) ?>
<?php $value = $this->userinfo ?>

<style>
.result{
	 margin-left: -8.5% !important;
	overflow: inherit;
}
</style>
<div class="page__bd">
        <div class="weui-form-preview">
        <div class="weui-form-preview__hd">
            <div class="weui-form-preview__item item">
                <label class="weui-form-preview__label"><i class="fa fa-file-text-o"></i>&nbsp;血常规(儿科)+超敏CRP(急)</label>
            </div>
        </div>
        <div class="weui-form-preview__bd main">
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">姓名：</label>
                <span class="weui-form-preview__value">谢羽晴</span>
            </div>
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">性别：</label>
                <span class="weui-form-preview__value">女</span>
            </div>
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">年龄：</label>
                <span class="weui-form-preview__value">5岁</span>
            </div>
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">床号：</label>
                <span class="weui-form-preview__value">YJ320173</span>
            </div>
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">检验科室：</label>
                <span class="weui-form-preview__value">急诊</span>
            </div>
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">开单医生：</label>
                <span class="weui-form-preview__value">田洪民 </span>
            </div>
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">开单时间：</label>
                <span class="weui-form-preview__value">2017-01-05</span>
            </div>
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">&nbsp;</label>
                <span class="weui-form-preview__value">&nbsp;</span>
            </div>
        </div>
    </div>
</div>
<div class="page__ft">
    <div class="weui-form-preview">
        <div class="weui-form-preview__hd" style="width:100%">
            <div class="weui-form-preview__item result" style="">
                <label class="weui-form-preview__label" style="margin-left:45% !important">检验结果</label><span class="weui-form-preview__value">&nbsp;</span>
            </div>
        </div>
        <div class="weui-form-preview__bd" style="height: 100%;padding:0;overflow-x: auto;">
        	<table border="0">
                <tbody><tr>
                    <td>检验结果</td>
                    <td>结果单位</td>
                    <td>结果状态</td>
                    <td>结果提示</td>
                    <td>参考范围下限</td>
                    <td>参考范围上限</td>
                    <td>样本类型</td>
                    <td>测试时间</td>
                    <td>操作者</td>
                </tr>
                <tr>
                    <td>27.90</td>
                    <td>%</td>
                    <td>5</td>
                    <td>z</td>
                    <td>20</td>
                    <td>40</td>
                    <td>全血</td>
                    <td>153144</td>
                    <td>刘保营</td>
                </tr>
                <tr>
                    <td>1.00</td>
                    <td>%</td>
                    <td>5</td>
                    <td>z</td>
                    <td>0.5</td>
                    <td>5</td>
                    <td>全血</td>
                    <td>153144</td>
                    <td>刘保营</td>
                </tr>
                <tr>
                    <td>0.00</td>
                    <td>%</td>
                    <td>5</td>
                    <td>z</td>
                    <td>0</td>
                    <td>1</td>
                    <td>全血</td>
                    <td>153144</td>
                    <td>刘保营</td>
                </tr>
                <tr>
                    <td>1.80</td>
                    <td>%</td>
                    <td>5</td>
                    <td>l</td>
                    <td>3</td>
                    <td>8</td>
                    <td>全血</td>
                    <td>153144</td>
                    <td>刘保营</td>
                </tr>
                <tr>
                    <td>6.16</td>
                    <td>10^9/L</td>
                    <td>5</td>
                    <td>z</td>
                    <td>2</td>
                    <td>7.7</td>
                    <td>全血</td>
                    <td>153144</td>
                    <td>刘保营</td>
                </tr>
                <tr>
                    <td>2.48</td>
                    <td>10^9/L</td>
                    <td>5</td>
                    <td>z</td>
                    <td>0.8</td>
                    <td>4</td>
                    <td>全血</td>
                    <td>153144</td>
                    <td>刘保营</td>
                </tr>
                <tr>
                    <td>0.00</td>
                    <td>10^9/L</td>
                    <td>5</td>
                    <td>z</td>
                    <td>0</td>
                    <td>0.1</td>
                    <td>全血</td>
                    <td>153144</td>
                    <td>刘保营</td>
                </tr>
                <tr>
                    <td>0.09</td>
                    <td>10^9/L</td>
                    <td>5</td>
                    <td>z</td>
                    <td>0.05</td>
                    <td>0.5</td>
                    <td>全血</td>
                    <td>153144</td>
                    <td>刘保营</td>
                </tr>
                <tr>
                    <td>0.16</td>
                    <td>10^9/L</td>
                    <td>5</td>
                    <td>z</td>
                    <td>0.12</td>
                    <td>0.8</td>
                    <td>全血</td>
                    <td>153144</td>
                    <td>刘保营</td>
                </tr>
                <tr>
                    <td>128.0</td>
                    <td>g/L</td>
                    <td>5</td>
                    <td>z</td>
                    <td>110</td>
                    <td>150</td>
                    <td>全血</td>
                    <td>153144</td>
                    <td>刘保营</td>
                </tr>
                <tr>
                    <td>38.20</td>
                    <td>%</td>
                    <td>5</td>
                    <td>z</td>
                    <td>36</td>
                    <td>50</td>
                    <td>全血</td>
                    <td>153144</td>
                    <td>刘保营</td>
                </tr>
                <tr>
                    <td>81.20</td>
                    <td>fL</td>
                    <td>5</td>
                    <td>l</td>
                    <td>86</td>
                    <td>100</td>
                    <td>全血</td>
                    <td>153144</td>
                    <td>刘保营</td>
                </tr>
                <tr>
                    <td>27.30</td>
                    <td>pg</td>
                    <td>5</td>
                    <td>z</td>
                    <td>26</td>
                    <td>31</td>
                    <td>全血</td>
                    <td>153144</td>
                    <td>刘保营</td>
                </tr>
                <tr>
                    <td>336</td>
                    <td>g/L</td>
                    <td>5</td>
                    <td>z</td>
                    <td>310</td>
                    <td>370</td>
                    <td>全血</td>
                    <td>153144</td>
                    <td>刘保营</td>
                </tr>
                <tr>
                    <td>34.2</td>
                    <td>fL</td>
                    <td>5</td>
                    <td>l</td>
                    <td>37</td>
                    <td>50</td>
                    <td>全血</td>
                    <td>153353</td>
                    <td>刘保营</td>
                </tr>
                <tr>
                    <td>234</td>
                    <td>10^9/L</td>
                    <td>5</td>
                    <td>z</td>
                    <td>100</td>
                    <td>300</td>
                    <td>全血</td>
                    <td>153144</td>
                    <td>刘保营</td>
                </tr>
                <tr>
                    <td>0.21</td>
                    <td>%</td>
                    <td>5</td>
                    <td>z</td>
                    <td>0.1</td>
                    <td>1.0</td>
                    <td>全血</td>
                    <td>153144</td>
                    <td>刘保营</td>
                </tr>
                <tr>
                    <td>8.90</td>
                    <td>fL</td>
                    <td>5</td>
                    <td>z</td>
                    <td>7.4</td>
                    <td>10.4</td>
                    <td>全血</td>
                    <td>153144</td>
                    <td>刘保营</td>
                </tr>
                <tr>
                    <td>16.50</td>
                    <td>fL</td>
                    <td>5</td>
                    <td>z</td>
                    <td>9</td>
                    <td>17</td>
                    <td>全血</td>
                    <td>153144</td>
                    <td>刘保营</td>
                </tr>
                <tr>
                    <td>69.30</td>
                    <td>%</td>
                    <td>5</td>
                    <td>z</td>
                    <td>45</td>
                    <td>77</td>
                    <td>全血</td>
                    <td>153144</td>
                    <td>刘保营</td>
                </tr>
                <tr>
                    <td>11.70</td>
                    <td>%</td>
                    <td>5</td>
                    <td>z</td>
                    <td>11</td>
                    <td>16</td>
                    <td>全血</td>
                    <td>153144</td>
                    <td>刘保营</td>
                </tr>
                <tr>
                    <td>4.71</td>
                    <td>10^12/L</td>
                    <td>5</td>
                    <td>z</td>
                    <td>3.5</td>
                    <td>5.0</td>
                    <td>全血</td>
                    <td>153144</td>
                    <td>刘保营</td>
                </tr>
                <tr>
                    <td>8.89</td>
                    <td>10^9/L</td>
                    <td>5</td>
                    <td>z</td>
                    <td>4</td>
                    <td>10</td>
                    <td>全血</td>
                    <td>153144</td>
                    <td>刘保营</td>
                </tr>
                <tr>
                    <td>4.62</td>
                    <td>mg/L</td>
                    <td>5</td>
                    <td>z</td>
                    <td>0</td>
                    <td>5</td>
                    <td>全血</td>
                    <td>153144</td>
                    <td>刘保营</td>
                </tr>
             </tbody></table>
        </div>
    </div>
    </div>