<?php $this->headTitle('检验单') ?>
<?php $this->headLink()->appendStylesheet('/assets/wx/report-query/index.css?t='.time()) ?>
<?php $this->headLink()->appendStylesheet('/assets/wx/appointment/my-reservation.css?t='.time()) ?>
<?php //$this->headScript()->appendFile('/assets/wx/report-query/jyd-index.js?t='.time()) ?>

<div class="page badge js_show">
    <div class="page__bd">
        <div class="weui-cells__title">以下是您的检验报告</div>
        <div class="weui-cells" style="    margin-bottom: 3px;">
            <div class="weui-cell">
                <label class="weui-form-preview__label" style="width: 5%;margin-top: 3px;"><i class="gi gi-user" style="color: #fc9953;"></i></label><br>
                <div class="weui-cell__bd">
                    <div class="weui-cell weui-cell_select">
                        <div class="weui-cell__bd">
                            <select class="weui-select" name="brid" id="select_user">
                                    <option value="2649285">雷延学 63212619931123456</option>
                                    <option value="889428">付毅 370121197306123456</option>
                                    <option value="1154292">刘莹 370103198604123456</option>
                            </select>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="main">
            <div class="weui-form-preview" style="height:140px">
                <div class="weui-form-preview__hd">
                    <div class="weui-form-preview__item item">
                        <label class="weui-form-preview__label"><i class="fa fa-file-text-o"></i>&nbsp;血常规(儿科)+超敏CRP(急)</label>
                        <button type="button" onclick="location.href='/wx/report-query/jyd-detail/sampleno/20170105G0050108'" class="weui-btn weui-btn_primary">查看详情</button>
                    </div>
                </div>
                <div class="weui-form-preview__bd">
                    <div class="weui-form-preview__item">
                        <label class="weui-form-preview__label">姓名</label>
                        <span class="weui-form-preview__value">谢羽晴</span>
                    </div>
                    <div class="weui-form-preview__item">
                        <label class="weui-form-preview__label">开单时间</label>
                        <span class="weui-form-preview__value">2017-01-05 15:31:44</span>
                    </div>
                    <div class="weui-form-preview__item">
                        <label class="weui-form-preview__label">状态</label>
                        <span class="weui-form-preview__value status">已打印</span>
                    </div>
                </div>
            </div>
            <div class="weui-form-preview" style="height:140px">
                <div class="weui-form-preview__hd">
                    <div class="weui-form-preview__item item">
                        <label class="weui-form-preview__label"><i class="fa fa-file-text-o"></i>&nbsp;血常规(儿科)+超敏CRP(急)</label>
                        <button type="button" onclick="location.href='/wx/report-query/jyd-detail/sampleno/20170105G0050108'" class="weui-btn weui-btn_primary">查看详情</button>
                    </div>
                </div>
                <div class="weui-form-preview__bd">
                    <div class="weui-form-preview__item">
                        <label class="weui-form-preview__label">姓名</label>
                        <span class="weui-form-preview__value">谢羽晴</span>
                    </div>
                    <div class="weui-form-preview__item">
                        <label class="weui-form-preview__label">开单时间</label>
                        <span class="weui-form-preview__value">2017-01-05 15:31:44</span>
                    </div>
                    <div class="weui-form-preview__item">
                        <label class="weui-form-preview__label">状态</label>
                        <span class="weui-form-preview__value status">已打印</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
