<!doctype html>
<html lang="zh">
<head>
<meta charset="utf-8">
<style type="text/css">
table td, table th {
	border: 1px solid #000;
}
</style>
</head>
<body>
	<table>
		<thead>
			<tr>
					<th>OPENID openid</th>
					<th>关系 relation</th>
					<th>姓名 name</th>
					<th>身份证号码 card_no</th>
					<th>手机号 phone</th>
					<th>是否有就诊卡号 is_patient_card</th>
					<th>就诊卡号码 patient_card</th>
					<th>日期 date</th>

			</tr>
		</thead>
		<tbody>
            <?php if ($this->data): foreach($this->data as $d):?>
            <tr>
					<td style="mso-number-format='\@'"><?php echo $d->openid ?></td>
					<td style="mso-number-format='\@'"><?php echo $d->relation ?></td>
					<td style="mso-number-format='\@'"><?php echo $d->name ?></td>
					<td style="mso-number-format='\@'"><?php echo $d->card_no ?></td>
					<td style="mso-number-format='\@'"><?php echo $d->phone ?></td>
					<td style="mso-number-format='\@'"><?php echo $d->is_patient_card ?></td>
					<td style="mso-number-format='\@'"><?php echo $d->patient_card ?></td>
					<td style="mso-number-format='yyyy-mm-dd h:i:s'"><?php echo $d->date ? date("Y-m-d H:i:s", strtotime($d->date)) : "" ?></td>
			</tr>
            <?php endforeach; endif; ?>
        </tbody>
	</table>
</body>
</html>
