<?php $this->headTitle('取消预约') ?>
<?php $this->headLink()->appendStylesheet('/assets/wx/appointment/dzf.css') ?>
<?php //$this->headScript()->appendFile('/assets/wx/abouts/list.js') ?>
<style>
button.weui-btn, input.weui-btn {
    width: 80%;
	margin-left:0
}
</style>
<div class="weui-panel__bd">
    <a href="javascript:void(0);" class="weui-media-box weui-media-box_appmsg">
        <div class="weui-media-box__hd">
            <i class="weui-icon-success weui-icon_msg"></i>
        </div>
        <div class="weui-media-box__bd">
            <h4 class="weui-media-box__title">取消成功</h4>
            <p class="weui-media-box__desc">您已成功取消预约，如有疑问，请联系客服！</p>
        </div>
    </a>
</div>

<div class="page__bd">
    <div class="weui-form-preview">
        <div class="weui-form-preview__hd">
            <div class="weui-form-preview__item item">
                <label class="weui-form-preview__label">详细信息</label>
            </div>
        </div>
        <div class="weui-form-preview__bd">
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">就诊时间</label>
                <span class="weui-form-preview__value red">2018-02-12</span>
                <span class="weui-form-preview__value red">周二 上午8：00-9：00</span>
            </div>
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">取号地点</label>
                <span class="weui-form-preview__value black">急诊挂号收费窗口</span>
            </div>
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">就诊地点</label>
                <span class="weui-form-preview__value red">门诊四楼东</span>
            </div>
        </div>
        <div class="weui-form-preview__bd">
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">科室</label>
                <span class="weui-form-preview__value black">消化内科</span>
            </div>
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">门诊类型</label>
                <span class="weui-form-preview__value black">专家门诊</span>
            </div>
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">状态</label>
                <span class="weui-form-preview__value black">已取消</span>
            </div>
        </div>
        <div class="weui-form-preview__bd">
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">就诊人</label>
                <span class="weui-form-preview__value black">张三</span>
            </div>
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">挂号费</label>
                <span class="weui-form-preview__value red">10元</span>
            </div>
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">提交时间</label>
                <span class="weui-form-preview__value">2018-02-10 10:02:01</span>
            </div>
        </div>
        <div class="footer">
            <button type="button"  onclick="location.href='/wx/appointment/yygh'" class="weui-btn weui-btn_primary">重新预约</button>
		</div>
    </div>
</div>