<?php $this->headTitle('详情页') ?>
<?php $this->headTitle('就诊须知') ?>
<?php $this->headLink()->appendStylesheet('/assets/default/news/detail.css') ?>
<?php $this->headScript()->appendFile('/assets/default/news/detail.js') ?>

<?php $d = $this->data ?>

<div class="container" style="margin-top:40px">
    
    <div class="row">
    
        <div class="col-lg-9 col-lg-9 col-sm-12 col-xs-12">
        
            <div class="page-header">
              <h1>就诊须知详情页 <small>Detail of News</small></h1>
            </div>
        
            <table class="table table-hover table-bordered table-rounded table-striped">
				<tr>
					<th>数据ID</th>
					<td><?php echo $d->id ?></td>
				</tr>
				<tr>
					<th>标题</th>
					<td><?php echo $d->title ?></td>
				</tr>
				<tr>
					<th>内容</th>
					<td><?php echo $d->intro ?></td>
				</tr>
            </table>
        
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">[面板模板]</h3>
                </div>
                <div class="panel-body">
                    ［面板内容面板内容面板内容面板内容面板内容面板内容面板内容面板内容面板内容面板内容面板内容］
                </div>
            </div>
        
        </div>
        
        
        <div class="col-lg-3 col-lg-3 col-sm-12 col-xs-12">
            <div class="list-group">
                <a href="#" class="list-group-item active">其它就诊须知</a>
                <?php if ($this->topData): foreach ($this->topData as $t): ?>
                <a href="/news/detail/id/<?php echo $t->id ?>" class="list-group-item">就诊须知<?php echo $t->id ?></a>
                <?php endforeach; endif; ?>
            </div>
            
        </div>
    
    </div>

</div>