<?php $this->headTitle('个人中心') ?>
<?php $this->headLink()->appendStylesheet('/assets/wx/person/index/index.css?t='.time()) ?>

<div class="page__hd">
    <h1 class="page__title">个人中心</h1>
</div>
<div class="panel panel-default panel-member">
    <div class="panel-body">
        <div class="text-center">
            <img src="http://airportvote.jnszkj.com/template/demo/images/avatars/1.jpg" class="img-circle" alt="image">
            <h4 class="thin">
                Marlon Brice
            </h4>
        </div>
    </div>
</div>
<div class="page__bd">
    <div class="weui-panel">
        <div class="weui-panel__hd">用户管理</div>
        <div class="weui-panel__bd">
            <div class="weui-media-box weui-media-box_small-appmsg">
                <div class="weui-cells">
                    <a class="weui-cell weui-cell_access" href="/wx/user-info/often">
                        <div class="weui-cell__hd"><img src="/assets/wx/img/hospital-service/jzr.svg" alt="" style="width:20px;margin-right:5px;display:block"></div>
                        <div class="weui-cell__bd weui-cell_primary">
                            <p>我的就诊人</p>
                        </div>
                        <span class="weui-cell__ft"></span>
                    </a>
                    <a class="weui-cell weui-cell_access" href="/wx/user/index">
                        <div class="weui-cell__hd"><img src="/assets/wx/img/hospital-service/user.png" alt="" style="width:20px;margin-right:5px;display:block"></div>
                        <div class="weui-cell__bd weui-cell_primary">
                            <p>个人信息</p>
                        </div>
                        <span class="weui-cell__ft"></span>
                    </a>
                    <a class="weui-cell weui-cell_access" href="/wx/person/collect">
                        <div class="weui-cell__hd"><img src="/assets/wx/img/hospital-service/sc.png" alt="" style="width:20px;margin-right:5px;display:block"></div>
                        <div class="weui-cell__bd weui-cell_primary">
                            <p>我的收藏</p>
                        </div>
                        <span class="weui-cell__ft"></span>
                    </a>
                </div>
            </div>
        </div>
    </div>
    <div class="weui-panel">
        <div class="weui-panel__hd">历史记录</div>
        <div class="weui-panel__bd">
            <div class="weui-media-box weui-media-box_small-appmsg">
                <div class="weui-cells">
                    <a class="weui-cell weui-cell_access" href="/wx/history/zd-record">
                        <div class="weui-cell__hd"><img src="/assets/wx/img/hospital-service/lszd.png" alt="" style="width:20px;margin-right:5px;display:block"></div>
                        <div class="weui-cell__bd weui-cell_primary">
                            <p>历史账单记录</p>
                        </div>
                        <span class="weui-cell__ft"></span>
                    </a>
                    <a class="weui-cell weui-cell_access" href="/wx/history/jz-record">
                        <div class="weui-cell__hd"><img src="/assets/wx/img/hospital-service/lsjz.png" alt="" style="width:20px;margin-right:5px;display:block"></div>
                        <div class="weui-cell__bd weui-cell_primary">
                            <p>历史预约记录</p>
                        </div>
                        <span class="weui-cell__ft"></span>
                    </a>
                    <a class="weui-cell weui-cell_access" href="/wx/report-query/index">
                        <div class="weui-cell__hd"><img src="/assets/wx/img/hospital-service/lsbg.png" alt="" style="width:20px;margin-right:5px;display:block"></div>
                        <div class="weui-cell__bd weui-cell_primary">
                            <p>历史检查记录</p>
                        </div>
                        <span class="weui-cell__ft"></span>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>