<?php $this->headTitle('资讯收藏') ?>
<?php $this->headLink()->appendStylesheet('/assets/wx/person/index/news-collect.css') ?>

<div class="page__hd">
    <h1 class="page__title">资讯收藏</h1>
</div>

<div class="weui-panel__bd">
<?php if($this->data): foreach ($this->data as $d): ?>
    <a href="/wx/person/news-detail/id/<?php echo $d->id ?> " class="weui-media-box weui-media-box_appmsg">
        <div class="weui-media-box__hd">
            <img class="weui-media-box__thumb" src="/uploads/180329/dj.jpg" alt="">
        </div>
        <div class="weui-media-box__bd">
            <h4 class="weui-media-box__title"><?php echo $d->title ?></h4>
            <p class="weui-media-box__desc"><?php echo date("Y-m-d",strtotime($d->date)) ?> </p>
        </div>
    </a>
<?php endforeach;else:?>
	<a href="javascript:void(0);" class="weui-media-box weui-media-box_appmsg" style="text-align: center;">
        <div class="weui-media-box__bd"> 暂无信息</div>
    </a>
<?php endif;?>
</div>