<?php $this->headTitle('我的收藏'); ?>
<?php $this->headLink()->appendStylesheet('/assets/wx/specialist/detail.css') ?>
<?php $d = $this->data ?>

<div class="weui-panel">
    <div class="weui-panel__bd">
        <div class="weui-media-box weui-media-box_text">
            <h4 class="weui-media-box__title"><?php echo $d->title ?></h4>
            <ul class="weui-media-box__info">
                <li class="weui-media-box__info__meta"><?php echo date("Y-m-d",strtotime($d->date))?></li>
                <li class="weui-media-box__info__meta weui-media-box__info__meta_extra"><?php echo $d->content?></li>
            </ul>
        </div>
    </div>
</div> 