<?php $this->headTitle('医师收藏') ?>
<?php $this->headLink()->appendStylesheet('/assets/wx/specialist/list.css') ?>
<style>
.weui-cell {
    border-bottom: 1px solid #eee;
}
</style>

<div class="page__hd">
    <h1 class="page__title">医师收藏</h1>
</div>
<div class="weui-cells">
<div class="weui-cells">
    <a href="" class="weui-cell_access">
        <div class="weui-cell">
            <div class="weui-cell__hd" style="position: relative;margin-right: 10px;">
                <img src="/assets/wx/appointment/doctor.png" style="width: 50px;display: block">
                <span class="weui-badge" style="position: absolute;top: -.4em;right: -.4em;"></span>
            </div>
            <div class="weui-cell__bd">
                <p class="name">赵世义</p>
                <p>消化内二科专家</p>
            </div>
        </div>
    </a>
</div>
</div>