<?php $this->headTitle('数据统计') ?>
<?php $this->headTitle('满意度调查') ?>
<?php $this->headLink()->appendStylesheet('/template/dist/css/plugins/jquery-dataTables.min.css') ?>
<?php $this->headScript()->appendFile('/template/dist/assets/plugins/jquery-datatables/js/jquery.dataTables.js') ?>
<?php $this->headScript()->appendFile('/template/dist/assets/plugins/jquery-datatables/js/dataTables.tableTools.js') ?>
<?php $this->headScript()->appendFile('/template/dist/assets/plugins/jquery-datatables/js/dataTables.bootstrap.js') ?>
<?php //$this->headScript()->appendFile('http://cdn.hcharts.cn/highcharts/highcharts.js') ?>
<?php //$this->headScript()->appendFile('http://cdn.hcharts.cn/highcharts/modules/exporting.js') ?>
<?php $this->headLink()->appendStylesheet('/assets/admin/satisfaction/statistics.css') ?>
<?php $this->headScript()->appendFile('/assets/admin/satisfaction/statistics.js') ?>

<div class="page-subheading page-subheading-md">
    <ol class="breadcrumb">
        <li><a href="javascript:;">控制面板</a></li>
        <li><a href="/admin/satisfaction/manage">满意度调查管理</a></li>
        <li class="active"><a href="javascript:;">数据统计</a></li>
    </ol>
</div>
<div class="page-heading page-heading-md">
    <h2>
        <i class="fa fa-bar-chart-o"></i> 满意度调查数据统计 
        <a href="javascript: history.go(-1)" class="btn btn-default pull-right">
    	    <i class="fa fa-chevron-left"></i> 返回</a>
    </h2>
</div>

<div class="container-fluid-md">
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h4 class="panel-title"><i class="fa fa-fw fa-bar-chart-o"></i> 数据占比统计</h4>

            <div class="panel-options">
            </div>
        </div>
        <ul class="nav nav-tabs">
			<li class="active"><a data-toggle="tab" href="#tab-is-open">是否开启   1是 2否</a></li>
			<li><a data-toggle="tab" href="#tab-title">标题</a></li>
			<li><a data-toggle="tab" href="#tab-start-time">开始时间</a></li>
			<li><a data-toggle="tab" href="#tab-end-time">结束时间</a></li>
			<li><a data-toggle="tab" href="#tab-date">日期</a></li>

        </ul>
        <div class="tab-content">
			<div id="tab-is-open" class="tab-pane active">
                <table class="table table-striped datatable">
                    <thead>
                    <tr>
                        <th>是否开启   1是 2否</th>
                        <th>数量</th>
                        <th>占比</th>
                        <th>&nbsp;</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php if ($this->dataIsOpen): 
                    foreach ($this->dataIsOpen as $d): 
                        $percent = sprintf('%.2f', 100 * $d->count / $this->totalRowsCount);
                    ?>
                    <tr>
                        <td><?php echo $d->is_open ?></td>
                        <td><?php echo $d->count ?></td>
                        <td><?php echo $percent ?>%</td>
                        <td>
                            <div class="progress progress-xs">
                                <div class="progress-bar" role="progressbar" 
                                    aria-valuenow="<?php echo $percent ?>" aria-valuemin="0" 
                                    aria-valuemax="100" style="width: <?php echo $percent ?>%;">
                                    <span class="sr-only"><?php echo $percent ?>%</span>
                                </div>
                            </div>
                        </td>
                    </tr>
                    <?php endforeach; endif; ?>
                    </tbody>
                    <tfoot>
                    </tfoot>
                </table>
            </div>
			<div id="tab-title" class="tab-pane">
                <table class="table table-striped datatable">
                    <thead>
                    <tr>
                        <th>标题</th>
                        <th>数量</th>
                        <th>占比</th>
                        <th>&nbsp;</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php if ($this->dataTitle): 
                    foreach ($this->dataTitle as $d): 
                        $percent = sprintf('%.2f', 100 * $d->count / $this->totalRowsCount);
                    ?>
                    <tr>
                        <td><?php echo $d->title ?></td>
                        <td><?php echo $d->count ?></td>
                        <td><?php echo $percent ?>%</td>
                        <td>
                            <div class="progress progress-xs">
                                <div class="progress-bar" role="progressbar" 
                                    aria-valuenow="<?php echo $percent ?>" aria-valuemin="0" 
                                    aria-valuemax="100" style="width: <?php echo $percent ?>%;">
                                    <span class="sr-only"><?php echo $percent ?>%</span>
                                </div>
                            </div>
                        </td>
                    </tr>
                    <?php endforeach; endif; ?>
                    </tbody>
                    <tfoot>
                    </tfoot>
                </table>
            </div>
			<div id="tab-start-time" class="tab-pane">
                <table class="table table-striped datatable">
                    <thead>
                    <tr>
                        <th>开始时间</th>
                        <th>数量</th>
                        <th>占比</th>
                        <th>&nbsp;</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php if ($this->dataStartTime): 
                    foreach ($this->dataStartTime as $d): 
                        $percent = sprintf('%.2f', 100 * $d->count / $this->totalRowsCount);
                    ?>
                    <tr>
                        <td><?php echo $d->start_time ?></td>
                        <td><?php echo $d->count ?></td>
                        <td><?php echo $percent ?>%</td>
                        <td>
                            <div class="progress progress-xs">
                                <div class="progress-bar" role="progressbar" 
                                    aria-valuenow="<?php echo $percent ?>" aria-valuemin="0" 
                                    aria-valuemax="100" style="width: <?php echo $percent ?>%;">
                                    <span class="sr-only"><?php echo $percent ?>%</span>
                                </div>
                            </div>
                        </td>
                    </tr>
                    <?php endforeach; endif; ?>
                    </tbody>
                    <tfoot>
                    </tfoot>
                </table>
            </div>
			<div id="tab-end-time" class="tab-pane">
                <table class="table table-striped datatable">
                    <thead>
                    <tr>
                        <th>结束时间</th>
                        <th>数量</th>
                        <th>占比</th>
                        <th>&nbsp;</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php if ($this->dataEndTime): 
                    foreach ($this->dataEndTime as $d): 
                        $percent = sprintf('%.2f', 100 * $d->count / $this->totalRowsCount);
                    ?>
                    <tr>
                        <td><?php echo $d->end_time ?></td>
                        <td><?php echo $d->count ?></td>
                        <td><?php echo $percent ?>%</td>
                        <td>
                            <div class="progress progress-xs">
                                <div class="progress-bar" role="progressbar" 
                                    aria-valuenow="<?php echo $percent ?>" aria-valuemin="0" 
                                    aria-valuemax="100" style="width: <?php echo $percent ?>%;">
                                    <span class="sr-only"><?php echo $percent ?>%</span>
                                </div>
                            </div>
                        </td>
                    </tr>
                    <?php endforeach; endif; ?>
                    </tbody>
                    <tfoot>
                    </tfoot>
                </table>
            </div>
			<div id="tab-date" class="tab-pane">
                <table class="table table-striped datatable">
                    <thead>
                    <tr>
                        <th>日期</th>
                        <th>数量</th>
                        <th>占比</th>
                        <th>&nbsp;</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php if ($this->dataDate): 
                    foreach ($this->dataDate as $d): 
                        $percent = sprintf('%.2f', 100 * $d->count / $this->totalRowsCount);
                    ?>
                    <tr>
                        <td><?php echo $d->date ?></td>
                        <td><?php echo $d->count ?></td>
                        <td><?php echo $percent ?>%</td>
                        <td>
                            <div class="progress progress-xs">
                                <div class="progress-bar" role="progressbar" 
                                    aria-valuenow="<?php echo $percent ?>" aria-valuemin="0" 
                                    aria-valuemax="100" style="width: <?php echo $percent ?>%;">
                                    <span class="sr-only"><?php echo $percent ?>%</span>
                                </div>
                            </div>
                        </td>
                    </tr>
                    <?php endforeach; endif; ?>
                    </tbody>
                    <tfoot>
                    </tfoot>
                </table>
            </div>

        </div>
    </div>
</div>