<?php $this->headTitle('修改密码') ?>
<?php $this->headLink()->appendStylesheet('/assets/wx/user/forgetpwd.css?t='.time()) ?>
 
<div class="page" style="opacity: 1;">
    <div>
        <div>
            <input placeholder="请输入原密码" class="id" maxlength="18">
        </div>
        <div style="margin-top: 5px;">
            <input placeholder="请输入新密码" class="id" maxlength="18">
        </div>
        <button class="next" style="touch-action: manipulation; -webkit-user-select: none; -webkit-user-drag: none; -webkit-tap-highlight-color: rgba(0, 0, 0, 0);">下一步
        </button>
    </div>
</div>