<?php $this->headTitle('个人信息') ?>
<?php $this->headLink()->appendStylesheet('/assets/wx/person/index/index.css?t='.time()) ?>
<?php $this->headLink()->appendStylesheet('/assets/wx/user/index.css') ?>
<div class="page__bd">
    <div class="panel panel-default panel-member">
        <div class="panel-body">
            <a href="pages-profile.html">
                <div class="text-center">
                    <img src="http://airportvote.jnszkj.com/template/demo/images/avatars/1.jpg" class="img-circle" alt="image">
                    <h4 class="thin">
                        Marlon Brice
                    </h4>
                </div>
            </a>
        </div>
    </div>
    <div class="weui-panel">
        <div class="weui-panel__hd">个人信息</div>
        <div class="weui-panel__bd">
            <div class="weui-media-box weui-media-box_small-appmsg">
                <div class="weui-cells">
                    <div class="weui-cell">
                        <div class="weui-cell__hd"><img src="/assets/wx/img/hospital-service/user.png" alt="" style="width:20px;margin-right:5px;display:block"></div>
                        <div class="weui-cell__bd">
                            <p>姓名</p>
                        </div>  
                        <div class="weui-cell__ft">张三</div>
                    </div>
                    <div class="weui-cell">
                        <div class="weui-cell__hd"><img src="/assets/wx/img/hospital-service/sfz.png" alt="" style="width:20px;margin-right:5px;display:block"></div>
                        <div class="weui-cell__bd">
                            <p>身份证号</p>
                        </div>
                        <div class="weui-cell__ft">12346451515754</div>
                    </div>
                    <div class="weui-cell">
                        <div class="weui-cell__hd"><img src="/assets/wx/img/hospital-service/phone.png" alt="" style="width:20px;margin-right:5px;display:block"></div>
                        <div class="weui-cell__bd">
                            <p>手机号</p>
                        </div>
                        <div class="weui-cell__ft">13548795412</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
