<?php $this->headTitle('注册') ?>
<?php $this->headLink()->appendStylesheet('/assets/wx/user/register.css?t='.time()) ?>
<?php $this->headScript()->appendFile('/assets/wx/user/register.js?t='.time()) ?>

<div class="page" style="opacity: 1;">
    <form>
        <div class="outside">
            <input class="tel" type="text" placeholder="手机号" maxlength="11" name="phone"  id="phone">
            <p class="phone active">请输入正确的手机号码</p>
        </div>
        <div class="outside">
            <input class="tel" type="text" placeholder="身份证号" maxlength="11" name="phone"  id="phone">
            <p class="phone active">请输入身份证号</p>
        </div>
        <div class="outside">
            <input class="pwd" type="password" placeholder="密码" maxlength="18"  name="pwd"  id="pwd">
            <p class="eye password active">请输入六位以上密码</p>
        </div>
        <div class="outside">
            <input class="pwd" type="password" placeholder="确认密码" maxlength="18" name="ppwd"  id="ppwd">
            <p class="ppwd">请再次输入密码</p>
        </div>
    </form>
    <div class="code" style="display:none">
        <input type="text" placeholder="输入验证码" name="code" id="code" data-info="请填写验证码。">
        <button id="code">短信验证码</button>
    </div>
    <button class="error" id="register"> 注册</button>
</div>

