<?php $this->headTitle('就诊流程') ?>
<?php $this->headLink()->appendStylesheet('/assets/wx/news/attendance-guide.css?t='.time()) ?>
<?php $this->headScript()->appendFile('/assets/wx/news/attendance-guide.js?t='.time()) ?>

<div>
    <ul id="data">
        <li data-type="1">
            <img src="/assets/wx/news/guide.png" class="headpic">
            <p class="right">就诊须知</p>
        </li>
        <li data-type="2">
            <img src="/assets/wx/news/guide.png" class="headpic">
            <p class="right">联系我们</p>
        </li>
    </ul>
    <div class="text-block" style="display: none;">
        <div class="content">
            <p class="title">就诊须知</p>
            <i class="icon-close"></i>
            <div class="intro">
            </div>
        </div>
    </div>
</div>
