<?php if($this->type == 3):$this->headTitle('注意事项');elseif($this->type == 2): $this->headTitle('就诊流程');elseif($this->type == 1): $this->headTitle('周边服务');endif;?>

<?php $this->headLink()->appendStylesheet('/assets/wx/specialist/detail.css') ?>
<?php $this->headScript()->appendFile('/assets/wx/specialist/detail.js') ?>

<?php $d = $this->data ?>

<div class="weui-panel">
    <div class="weui-panel__bd">
        <div class="weui-media-box weui-media-box_text">
            <h4 class="weui-media-box__title"><?php echo $d->title ?></h4>
            <ul class="weui-media-box__info">
                <li class="weui-media-box__info__meta"><?php echo date("Y-m-d",strtotime($d->date))?></li>
                <li class="weui-media-box__info__meta weui-media-box__info__meta_extra"><?php echo $d->intro?></li>
            </ul>
        </div>
    </div>
</div> 