<?php $this->headTitle('首页') ?>
<?php $this->headLink()->appendStylesheet('/assets/wx/scan/index.css?t='.time()) ?>
<?php //$this->headScript()->appendFile('/assets/wx/scan/scan.js?t='.time()) ?>

<div class="page__bd">
    <div class="weui-form-preview">
        <div class="weui-form-preview__hd">
            <div class="weui-form-preview__item item">
                <label class="weui-form-preview__label"><i class="fa fa-user"></i>&nbsp;个人信息</label>
            </div>
        </div>
        <div class="weui-form-preview__bd main">
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">姓名:</label>
                <span class="weui-form-preview__value">孙晓亮</span>
            </div>
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">年龄:</label>
                <span class="weui-form-preview__value">14</span>
            </div>
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">性别:</label>
                <span class="weui-form-preview__value">男</span>
            </div>
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">卡号:</label>
                <span class="weui-form-preview__value">123456</span>
            </div>
            <div class="weui-form-preview__item" style="width:100%">
                <label class="weui-form-preview__label">身份证号:</label>
                <span class="weui-form-preview__value">123457864165486463145</span>
            </div>
        </div>
    </div>
    <div class="page grid js_show">
        <div class="weui-panel__hd">用户操作</div>
        <div class="weui-grids">
            <a href="/wx/report-query/jyd-index" class="weui-grid">
                <div class="weui-grid__icon" style="    width: 55px;">
                    <img src="/assets/wx/img/hospital-service/jianchadan.svg">
                </div>
                <p class="weui-grid__label">检验单</p>
            </a>
            <a href="/wx/report-query/index" class="weui-grid">
                <div class="weui-grid__icon">
                    <img src="/assets/wx/img/hospital-service/jianchadan.svg">
                </div>
                <p class="weui-grid__label">检查单</p>
            </a>
            <a href="/wx/history/zd-record" class="weui-grid">
                <div class="weui-grid__icon">
                    <img src="/assets/wx/img/hospital-service/jianchadan.svg">
                </div>
                <p class="weui-grid__label">历史账单</p>
            </a>
            <a href="/wx/report-query/index" class="weui-grid">
                <div class="weui-grid__icon">
                    <img src="/assets/wx/img/hospital-service/jianchadan.svg">
                </div>
                <p class="weui-grid__label">住院充值记录</p>
            </a>
            <a href="/wx/report-query/index" class="weui-grid">
                <div class="weui-grid__icon">
                    <img src="/assets/wx/img/hospital-service/zycz.svg">
                </div>
                <p class="weui-grid__label">住院充值</p>
            </a>
        </div>
        <div class="weui-panel">
            <div class="weui-panel__bd">
                <div class="weui-media-box weui-media-box_small-appmsg">
                    <div class="weui-cells">
                        <a class="weui-cell weui-cell_access" href="/wx/history/zd-record">
                            <div class="weui-cell__hd"><img src="/assets/wx/img/hospital-service/lszd.png" alt="" style="width:20px;margin-right:5px;display:block"></div>
                            <div class="weui-cell__bd weui-cell_primary">
                                <p>历史账单记录</p>
                            </div>
                            <span class="weui-cell__ft"></span>
                        </a>
                        <a class="weui-cell weui-cell_access" href="/wx/report-query/index">
                            <div class="weui-cell__hd"><img src="/assets/wx/img/hospital-service/lsbg.png" alt="" style="width:20px;margin-right:5px;display:block"></div>
                            <div class="weui-cell__bd weui-cell_primary">
                                <p>住院充值记录</p>
                            </div>
                            <span class="weui-cell__ft"></span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>