<?php $this->headTitle('扫一扫') ?>
<?php //$this->headLink()->appendStylesheet('/assets/wx/delivery/scan.css?t='.time()) ?>
<?php $this->headScript()->appendFile('/libs/vue/vue.min.js') ?>
<?php $this->headScript()->appendFile('http://res.wx.qq.com/open/js/jweixin-1.1.0.js') ?>
<?php $this->headScript()->appendFile('/assets/wx/scan/scan.js?t='.time()) ?>
<?php
/**
 * 使能微信JS调用 
 */
$jsApiList = array(
    'scanQRCode',
);
$debug = false;
echo Szkj_Helper_WXBiz::getJsConfigDefineScript($jsApiList, $debug);
?>
<div style="margin:5px">正在调用扫一扫...</div> 
 <a href="javascript:;" class="weui-btn weui-btn_default" id="scanQRCode">扫一扫</a>

