<?php $this->headTitle('满意度调查') ?>
<?php $this->headLink()->appendStylesheet('/assets/wx/satisfaction/warn.css?t='.time()) ?>
<div class="page icons js_show">
    <div class="page__bd page__bd_spacing">
		<img src="/assets/wx/satisfaction/myd.jpg">
        <div class="icon-box__ctn">
            <h3 class="icon-box__title">暂无题目</h3>
            <p class="icon-box__desc">您好，该调查问卷暂未添加题目，感谢您的关注。</p>
        </div>
    </div>
    <div class="page__ft">
    	<a href="/wx/satisfaction/index" class="weui-btn weui-btn_default">返回</a>
    </div>
</div>
