<?php $this->headTitle('满意度调查') ?>
<?php $this->headLink()->appendStylesheet('/assets/wx/satisfaction/warn.css?t='.time()) ?>
<style>
.weui-icon-success{
	color:#09bb07 !important
}
</style>

<div class="page icons js_show">
    <div class="page__bd page__bd_spacing">
		<i class="weui-icon-success weui-icon_msg"></i>
        <div class="icon-box__ctn">
            <h3 class="icon-box__title">感谢您的参与</h3>
            <p class="icon-box__desc">根据您的意见，我们将对医院的服务进行反馈和监督，提高您的就医体验。</p>
        </div>
    </div>
    <div class="page__ft">
    	<a href="/wx/satisfaction/index" class="weui-btn weui-btn_default">返回</a>
    </div>
</div>
