<?php $this->headTitle('查看页') ?>
<?php $this->headTitle('系统角色') ?>
<?php $this->headLink()->appendStylesheet('/assets/admin/sys-role/view.css') ?>
<?php $this->headScript()->appendFile('/assets/admin/sys-role/view.js') ?>

<?php $d = $this->data ?>

<div class="page-subheading page-subheading-md">
    <ol class="breadcrumb">
        <li><a href="javascript:;">控制面板</a></li>
        <li><a href="/admin/sys-role/manage">系统角色管理</a></li>
        <li class="active"><a href="javascript:;">查看</a></li>
    </ol>
</div>
<div class="page-heading page-heading-md">
    <h2><i class="fa fa-info-circle"></i> 系统角色详情 <a href="javascript: history.go(-1)" class="btn btn-default">
    	    <i class="fa fa-chevron-left"></i> 返回</a></h2>
</div>

<div class="container-fluid-md">
    <div class="panel panel-success">
        <div class="panel-heading">
            <h4 class="panel-title"><i class="fa fa-info-circle"></i> 系统角色</h4>

            <div class="panel-options">
                <a href="#" data-rel="collapse"><i class="fa fa-fw fa-minus"></i></a>
                <a href="#" data-rel="close"><i class="fa fa-fw fa-times"></i></a>
            </div>
        </div>
        <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-striped table-hover table-detail-view">
                    <tbody>
				<tr>
					<th>角色名称</th>
					<td><?php echo $d->name ?></td>
				</tr>
				<tr>
					<th>管理界面布局</th>
					<td><?php echo $d->layout_admin ?></td>
				</tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>