<?php $this->headTitle('特色医技') ?>
<?php $this->headLink()->appendStylesheet('/assets/wx/specialist/list.css') ?>
<?php $this->headScript()->appendFile('/assets/wx/feature-skill/list.js') ?>

<style>
.weui-media-box {padding: 0px 15px 10px 15px;}
.weui-panel__ft{text-align: center;}
.weui-cell {padding: 10px 15px 10px 15px;}
</style>
<div class="page__hd">
    <h1 class="page__title">特色医技</h1>
</div>
<div class="weui-panel weui-panel_access">
    <div class="weui-panel__bd">
        <div class="weui-media-box weui-media-box_small-appmsg" style="padding: 0px 10px 0px 0px;">
            <div class="weui-cells main">
            
            </div>
            <div class="weui-panel__ft" style="text-align: center;">
                <a href="javascript:void(0);" class="weui-cell weui-cell_access weui-cell_link">
                    <div class="weui-cell__bd more"></div>
                </a>
            </div>
        </div>
    </div>
</div>