<?php $this->headTitle('查看页') ?>
<?php $this->headTitle('专家介绍') ?>
<?php $this->headLink()->appendStylesheet('/assets/admin/specialist/view.css') ?>
<?php $this->headScript()->appendFile('/assets/admin/specialist/view.js') ?>

<?php $d = $this->data ?>

<div class="page-subheading page-subheading-md">
    <ol class="breadcrumb">
        <li><a href="javascript:;">控制面板</a></li>
        <li><a href="/admin/specialist/manage">专家介绍管理</a></li>
        <li class="active"><a href="javascript:;">查看</a></li>
    </ol>
</div>
<div class="page-heading page-heading-md">
    <h2>
        <i class="fa fa-info-circle"></i> 专家介绍详情 
        <a href="javascript: history.go(-1)" class="btn btn-default pull-right">
    	    <i class="fa fa-chevron-left"></i> 返回</a>
    </h2>
</div>

<div class="container-fluid-md">
    <div class="panel panel-default">
        <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-striped table-bordered table-detail-view">
                    <tbody>
				<tr>
					<th>类型</th>
					<td><?php echo $d->type ?></td>
				</tr>
				<tr>
					<th>姓名</th>
					<td><?php echo $d->name ?></td>
				</tr>
				<tr>
					<th>照片</th>
					<td>
                        <?php if ($d->photo): ?>
                        <a href="<?php echo $d->photo ?>" target="_blank">
                            <img src="<?php echo Szkj_Helper_Thumb::getSpecifiedThumb($d->photo, "l") ?>" class="thumbnail" style="max-width:500px" />
                        </a>
                        <?php endif; ?>
					</td>
				</tr>
				<tr>
					<th>简介</th>
					<td><?php echo $d->intro ?></td>
				</tr>
				<tr>
					<th>日期</th>
					<td><?php echo $d->date ? date("Y-m-d", strtotime($d->date)) : "" ?></td>
				</tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>